/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BetaCrashLogResponse from '../model/BetaCrashLogResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* BetaCrashLogs service.
* @module api/BetaCrashLogsApi
* @version 4.1
*/
export default class BetaCrashLogsApi {

    /**
    * Constructs a new BetaCrashLogsApi. 
    * @alias module:api/BetaCrashLogsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the betaCrashLogsGetInstance operation.
     * @callback module:api/BetaCrashLogsApi~betaCrashLogsGetInstanceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/BetaCrashLogResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} id the id of the requested resource
     * @param {Object} opts Optional parameters
     * @param {Array.<module:model/String>} [fieldsBetaCrashLogs] the fields to include for returned resources of type betaCrashLogs
     * @param {module:api/BetaCrashLogsApi~betaCrashLogsGetInstanceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/BetaCrashLogResponse}
     */
    betaCrashLogsGetInstance(id, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling betaCrashLogsGetInstance");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'fields[betaCrashLogs]': this.apiClient.buildCollectionParam(opts['fieldsBetaCrashLogs'], 'csv')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['itc-bearer-token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = BetaCrashLogResponse;
      return this.apiClient.callApi(
        '/v1/betaCrashLogs/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
