/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues', function() {
    it('should create an instance of BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues', function() {
      // uncomment below and update the code to test BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
      //var instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
      //expect(instance).to.be.a(AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues);
    });

    it('should have the property viewCount (base name: "viewCount")', function() {
      // uncomment below and update the code to test the property viewCount
      //var instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
      //expect(instance).to.be();
    });

    it('should have the property acceptedCount (base name: "acceptedCount")', function() {
      // uncomment below and update the code to test the property acceptedCount
      //var instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
      //expect(instance).to.be();
    });

    it('should have the property didNotAcceptCount (base name: "didNotAcceptCount")', function() {
      // uncomment below and update the code to test the property didNotAcceptCount
      //var instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
      //expect(instance).to.be();
    });

    it('should have the property didNotMeetCriteriaCount (base name: "didNotMeetCriteriaCount")', function() {
      // uncomment below and update the code to test the property didNotMeetCriteriaCount
      //var instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
      //expect(instance).to.be();
    });

    it('should have the property notRelevantRatio (base name: "notRelevantRatio")', function() {
      // uncomment below and update the code to test the property notRelevantRatio
      //var instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
      //expect(instance).to.be();
    });

    it('should have the property notClearRatio (base name: "notClearRatio")', function() {
      // uncomment below and update the code to test the property notClearRatio
      //var instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
      //expect(instance).to.be();
    });

    it('should have the property notInterestingRatio (base name: "notInterestingRatio")', function() {
      // uncomment below and update the code to test the property notInterestingRatio
      //var instance = new AppStoreConnectApi.BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();
      //expect(instance).to.be();
    });

  });

}));
