/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.CiWorkflowAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CiWorkflowAttributes', function() {
    it('should create an instance of CiWorkflowAttributes', function() {
      // uncomment below and update the code to test CiWorkflowAttributes
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be.a(AppStoreConnectApi.CiWorkflowAttributes);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property branchStartCondition (base name: "branchStartCondition")', function() {
      // uncomment below and update the code to test the property branchStartCondition
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property tagStartCondition (base name: "tagStartCondition")', function() {
      // uncomment below and update the code to test the property tagStartCondition
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property pullRequestStartCondition (base name: "pullRequestStartCondition")', function() {
      // uncomment below and update the code to test the property pullRequestStartCondition
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property scheduledStartCondition (base name: "scheduledStartCondition")', function() {
      // uncomment below and update the code to test the property scheduledStartCondition
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property manualBranchStartCondition (base name: "manualBranchStartCondition")', function() {
      // uncomment below and update the code to test the property manualBranchStartCondition
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property manualTagStartCondition (base name: "manualTagStartCondition")', function() {
      // uncomment below and update the code to test the property manualTagStartCondition
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property manualPullRequestStartCondition (base name: "manualPullRequestStartCondition")', function() {
      // uncomment below and update the code to test the property manualPullRequestStartCondition
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property actions (base name: "actions")', function() {
      // uncomment below and update the code to test the property actions
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property isEnabled (base name: "isEnabled")', function() {
      // uncomment below and update the code to test the property isEnabled
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property isLockedForEditing (base name: "isLockedForEditing")', function() {
      // uncomment below and update the code to test the property isLockedForEditing
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property clean (base name: "clean")', function() {
      // uncomment below and update the code to test the property clean
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property containerFilePath (base name: "containerFilePath")', function() {
      // uncomment below and update the code to test the property containerFilePath
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

    it('should have the property lastModifiedDate (base name: "lastModifiedDate")', function() {
      // uncomment below and update the code to test the property lastModifiedDate
      //var instance = new AppStoreConnectApi.CiWorkflowAttributes();
      //expect(instance).to.be();
    });

  });

}));
