/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.GameCenterMatchmakingRuleCreateRequestDataAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GameCenterMatchmakingRuleCreateRequestDataAttributes', function() {
    it('should create an instance of GameCenterMatchmakingRuleCreateRequestDataAttributes', function() {
      // uncomment below and update the code to test GameCenterMatchmakingRuleCreateRequestDataAttributes
      //var instance = new AppStoreConnectApi.GameCenterMatchmakingRuleCreateRequestDataAttributes();
      //expect(instance).to.be.a(AppStoreConnectApi.GameCenterMatchmakingRuleCreateRequestDataAttributes);
    });

    it('should have the property referenceName (base name: "referenceName")', function() {
      // uncomment below and update the code to test the property referenceName
      //var instance = new AppStoreConnectApi.GameCenterMatchmakingRuleCreateRequestDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AppStoreConnectApi.GameCenterMatchmakingRuleCreateRequestDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new AppStoreConnectApi.GameCenterMatchmakingRuleCreateRequestDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property expression (base name: "expression")', function() {
      // uncomment below and update the code to test the property expression
      //var instance = new AppStoreConnectApi.GameCenterMatchmakingRuleCreateRequestDataAttributes();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new AppStoreConnectApi.GameCenterMatchmakingRuleCreateRequestDataAttributes();
      //expect(instance).to.be();
    });

  });

}));
