/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.GameCenterChallengeAttributes();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GameCenterChallengeAttributes', function() {
    it('should create an instance of GameCenterChallengeAttributes', function() {
      // uncomment below and update the code to test GameCenterChallengeAttributes
      //var instance = new AppStoreConnectApi.GameCenterChallengeAttributes();
      //expect(instance).to.be.a(AppStoreConnectApi.GameCenterChallengeAttributes);
    });

    it('should have the property referenceName (base name: "referenceName")', function() {
      // uncomment below and update the code to test the property referenceName
      //var instance = new AppStoreConnectApi.GameCenterChallengeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property vendorIdentifier (base name: "vendorIdentifier")', function() {
      // uncomment below and update the code to test the property vendorIdentifier
      //var instance = new AppStoreConnectApi.GameCenterChallengeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property archived (base name: "archived")', function() {
      // uncomment below and update the code to test the property archived
      //var instance = new AppStoreConnectApi.GameCenterChallengeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property challengeType (base name: "challengeType")', function() {
      // uncomment below and update the code to test the property challengeType
      //var instance = new AppStoreConnectApi.GameCenterChallengeAttributes();
      //expect(instance).to.be();
    });

    it('should have the property repeatable (base name: "repeatable")', function() {
      // uncomment below and update the code to test the property repeatable
      //var instance = new AppStoreConnectApi.GameCenterChallengeAttributes();
      //expect(instance).to.be();
    });

  });

}));
