/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.AlternativeDistributionDomainsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlternativeDistributionDomainsApi', function() {
    describe('alternativeDistributionDomainsCreateInstance', function() {
      it('should call alternativeDistributionDomainsCreateInstance successfully', function(done) {
        //uncomment below and update the code to test alternativeDistributionDomainsCreateInstance
        //instance.alternativeDistributionDomainsCreateInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('alternativeDistributionDomainsDeleteInstance', function() {
      it('should call alternativeDistributionDomainsDeleteInstance successfully', function(done) {
        //uncomment below and update the code to test alternativeDistributionDomainsDeleteInstance
        //instance.alternativeDistributionDomainsDeleteInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('alternativeDistributionDomainsGetCollection', function() {
      it('should call alternativeDistributionDomainsGetCollection successfully', function(done) {
        //uncomment below and update the code to test alternativeDistributionDomainsGetCollection
        //instance.alternativeDistributionDomainsGetCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('alternativeDistributionDomainsGetInstance', function() {
      it('should call alternativeDistributionDomainsGetInstance successfully', function(done) {
        //uncomment below and update the code to test alternativeDistributionDomainsGetInstance
        //instance.alternativeDistributionDomainsGetInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
