/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.InAppPurchaseAvailabilitiesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InAppPurchaseAvailabilitiesApi', function() {
    describe('inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated', function() {
      it('should call inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated successfully', function(done) {
        //uncomment below and update the code to test inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated
        //instance.inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship', function() {
      it('should call inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship successfully', function(done) {
        //uncomment below and update the code to test inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship
        //instance.inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('inAppPurchaseAvailabilitiesCreateInstance', function() {
      it('should call inAppPurchaseAvailabilitiesCreateInstance successfully', function(done) {
        //uncomment below and update the code to test inAppPurchaseAvailabilitiesCreateInstance
        //instance.inAppPurchaseAvailabilitiesCreateInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('inAppPurchaseAvailabilitiesGetInstance', function() {
      it('should call inAppPurchaseAvailabilitiesGetInstance successfully', function(done) {
        //uncomment below and update the code to test inAppPurchaseAvailabilitiesGetInstance
        //instance.inAppPurchaseAvailabilitiesGetInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
