/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.PassTypeIdsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PassTypeIdsApi', function() {
    describe('passTypeIdsCertificatesGetToManyRelated', function() {
      it('should call passTypeIdsCertificatesGetToManyRelated successfully', function(done) {
        //uncomment below and update the code to test passTypeIdsCertificatesGetToManyRelated
        //instance.passTypeIdsCertificatesGetToManyRelated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('passTypeIdsCertificatesGetToManyRelationship', function() {
      it('should call passTypeIdsCertificatesGetToManyRelationship successfully', function(done) {
        //uncomment below and update the code to test passTypeIdsCertificatesGetToManyRelationship
        //instance.passTypeIdsCertificatesGetToManyRelationship(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('passTypeIdsCreateInstance', function() {
      it('should call passTypeIdsCreateInstance successfully', function(done) {
        //uncomment below and update the code to test passTypeIdsCreateInstance
        //instance.passTypeIdsCreateInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('passTypeIdsDeleteInstance', function() {
      it('should call passTypeIdsDeleteInstance successfully', function(done) {
        //uncomment below and update the code to test passTypeIdsDeleteInstance
        //instance.passTypeIdsDeleteInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('passTypeIdsGetCollection', function() {
      it('should call passTypeIdsGetCollection successfully', function(done) {
        //uncomment below and update the code to test passTypeIdsGetCollection
        //instance.passTypeIdsGetCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('passTypeIdsGetInstance', function() {
      it('should call passTypeIdsGetInstance successfully', function(done) {
        //uncomment below and update the code to test passTypeIdsGetInstance
        //instance.passTypeIdsGetInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('passTypeIdsUpdateInstance', function() {
      it('should call passTypeIdsUpdateInstance successfully', function(done) {
        //uncomment below and update the code to test passTypeIdsUpdateInstance
        //instance.passTypeIdsUpdateInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
