/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.SubscriptionGroupsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubscriptionGroupsApi', function() {
    describe('subscriptionGroupsCreateInstance', function() {
      it('should call subscriptionGroupsCreateInstance successfully', function(done) {
        //uncomment below and update the code to test subscriptionGroupsCreateInstance
        //instance.subscriptionGroupsCreateInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriptionGroupsDeleteInstance', function() {
      it('should call subscriptionGroupsDeleteInstance successfully', function(done) {
        //uncomment below and update the code to test subscriptionGroupsDeleteInstance
        //instance.subscriptionGroupsDeleteInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriptionGroupsGetInstance', function() {
      it('should call subscriptionGroupsGetInstance successfully', function(done) {
        //uncomment below and update the code to test subscriptionGroupsGetInstance
        //instance.subscriptionGroupsGetInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriptionGroupsSubscriptionGroupLocalizationsGetToManyRelated', function() {
      it('should call subscriptionGroupsSubscriptionGroupLocalizationsGetToManyRelated successfully', function(done) {
        //uncomment below and update the code to test subscriptionGroupsSubscriptionGroupLocalizationsGetToManyRelated
        //instance.subscriptionGroupsSubscriptionGroupLocalizationsGetToManyRelated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriptionGroupsSubscriptionGroupLocalizationsGetToManyRelationship', function() {
      it('should call subscriptionGroupsSubscriptionGroupLocalizationsGetToManyRelationship successfully', function(done) {
        //uncomment below and update the code to test subscriptionGroupsSubscriptionGroupLocalizationsGetToManyRelationship
        //instance.subscriptionGroupsSubscriptionGroupLocalizationsGetToManyRelationship(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriptionGroupsSubscriptionsGetToManyRelated', function() {
      it('should call subscriptionGroupsSubscriptionsGetToManyRelated successfully', function(done) {
        //uncomment below and update the code to test subscriptionGroupsSubscriptionsGetToManyRelated
        //instance.subscriptionGroupsSubscriptionsGetToManyRelated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriptionGroupsSubscriptionsGetToManyRelationship', function() {
      it('should call subscriptionGroupsSubscriptionsGetToManyRelationship successfully', function(done) {
        //uncomment below and update the code to test subscriptionGroupsSubscriptionsGetToManyRelationship
        //instance.subscriptionGroupsSubscriptionsGetToManyRelationship(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('subscriptionGroupsUpdateInstance', function() {
      it('should call subscriptionGroupsUpdateInstance successfully', function(done) {
        //uncomment below and update the code to test subscriptionGroupsUpdateInstance
        //instance.subscriptionGroupsUpdateInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
