/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AppStoreConnectApi);
  }
}(this, function(expect, AppStoreConnectApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AppStoreConnectApi.WinBackOffersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WinBackOffersApi', function() {
    describe('winBackOffersCreateInstance', function() {
      it('should call winBackOffersCreateInstance successfully', function(done) {
        //uncomment below and update the code to test winBackOffersCreateInstance
        //instance.winBackOffersCreateInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('winBackOffersDeleteInstance', function() {
      it('should call winBackOffersDeleteInstance successfully', function(done) {
        //uncomment below and update the code to test winBackOffersDeleteInstance
        //instance.winBackOffersDeleteInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('winBackOffersGetInstance', function() {
      it('should call winBackOffersGetInstance successfully', function(done) {
        //uncomment below and update the code to test winBackOffersGetInstance
        //instance.winBackOffersGetInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('winBackOffersPricesGetToManyRelated', function() {
      it('should call winBackOffersPricesGetToManyRelated successfully', function(done) {
        //uncomment below and update the code to test winBackOffersPricesGetToManyRelated
        //instance.winBackOffersPricesGetToManyRelated(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('winBackOffersPricesGetToManyRelationship', function() {
      it('should call winBackOffersPricesGetToManyRelationship successfully', function(done) {
        //uncomment below and update the code to test winBackOffersPricesGetToManyRelationship
        //instance.winBackOffersPricesGetToManyRelationship(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('winBackOffersUpdateInstance', function() {
      it('should call winBackOffersUpdateInstance successfully', function(done) {
        //uncomment below and update the code to test winBackOffersUpdateInstance
        //instance.winBackOffersUpdateInstance(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
