/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlternativeDistributionPackageVersionAttributes model module.
 * @module model/AlternativeDistributionPackageVersionAttributes
 * @version 4.1
 */
class AlternativeDistributionPackageVersionAttributes {
    /**
     * Constructs a new <code>AlternativeDistributionPackageVersionAttributes</code>.
     * @alias module:model/AlternativeDistributionPackageVersionAttributes
     */
    constructor() { 
        
        AlternativeDistributionPackageVersionAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AlternativeDistributionPackageVersionAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlternativeDistributionPackageVersionAttributes} obj Optional instance to populate.
     * @return {module:model/AlternativeDistributionPackageVersionAttributes} The populated <code>AlternativeDistributionPackageVersionAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlternativeDistributionPackageVersionAttributes();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('urlExpirationDate')) {
                obj['urlExpirationDate'] = ApiClient.convertToType(data['urlExpirationDate'], 'Date');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('fileChecksum')) {
                obj['fileChecksum'] = ApiClient.convertToType(data['fileChecksum'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AlternativeDistributionPackageVersionAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AlternativeDistributionPackageVersionAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }
        // ensure the json data is a string
        if (data['fileChecksum'] && !(typeof data['fileChecksum'] === 'string' || data['fileChecksum'] instanceof String)) {
            throw new Error("Expected the field `fileChecksum` to be a primitive type in the JSON string but got " + data['fileChecksum']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }

        return true;
    }


}



/**
 * @member {String} url
 */
AlternativeDistributionPackageVersionAttributes.prototype['url'] = undefined;

/**
 * @member {Date} urlExpirationDate
 */
AlternativeDistributionPackageVersionAttributes.prototype['urlExpirationDate'] = undefined;

/**
 * @member {String} version
 */
AlternativeDistributionPackageVersionAttributes.prototype['version'] = undefined;

/**
 * @member {String} fileChecksum
 */
AlternativeDistributionPackageVersionAttributes.prototype['fileChecksum'] = undefined;

/**
 * @member {module:model/AlternativeDistributionPackageVersionAttributes.StateEnum} state
 */
AlternativeDistributionPackageVersionAttributes.prototype['state'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
AlternativeDistributionPackageVersionAttributes['StateEnum'] = {

    /**
     * value: "COMPLETED"
     * @const
     */
    "COMPLETED": "COMPLETED",

    /**
     * value: "REPLACED"
     * @const
     */
    "REPLACED": "REPLACED"
};



export default AlternativeDistributionPackageVersionAttributes;

