/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppCustomProductPageVersion from './AppCustomProductPageVersion';
import AppKeyword from './AppKeyword';
import AppPreviewSet from './AppPreviewSet';
import AppScreenshotSet from './AppScreenshotSet';
import AppScreenshotSetAttributes from './AppScreenshotSetAttributes';
import AppScreenshotSetRelationships from './AppScreenshotSetRelationships';
import ResourceLinks from './ResourceLinks';

/**
 * The AppCustomProductPageLocalizationsResponseIncludedInner model module.
 * @module model/AppCustomProductPageLocalizationsResponseIncludedInner
 * @version 4.1
 */
class AppCustomProductPageLocalizationsResponseIncludedInner {
    /**
     * Constructs a new <code>AppCustomProductPageLocalizationsResponseIncludedInner</code>.
     * @alias module:model/AppCustomProductPageLocalizationsResponseIncludedInner
     * @param {(module:model/AppCustomProductPageVersion|module:model/AppKeyword|module:model/AppPreviewSet|module:model/AppScreenshotSet)} instance The actual instance to initialize AppCustomProductPageLocalizationsResponseIncludedInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "AppCustomProductPageVersion") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AppCustomProductPageVersion.validateJSON(instance); // throw an exception if no match
                // create AppCustomProductPageVersion from JS object
                this.actualInstance = AppCustomProductPageVersion.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AppCustomProductPageVersion
            errorMessages.push("Failed to construct AppCustomProductPageVersion: " + err)
        }

        try {
            if (typeof instance === "AppKeyword") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AppKeyword.validateJSON(instance); // throw an exception if no match
                // create AppKeyword from JS object
                this.actualInstance = AppKeyword.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AppKeyword
            errorMessages.push("Failed to construct AppKeyword: " + err)
        }

        try {
            if (typeof instance === "AppPreviewSet") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AppPreviewSet.validateJSON(instance); // throw an exception if no match
                // create AppPreviewSet from JS object
                this.actualInstance = AppPreviewSet.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AppPreviewSet
            errorMessages.push("Failed to construct AppPreviewSet: " + err)
        }

        try {
            if (typeof instance === "AppScreenshotSet") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AppScreenshotSet.validateJSON(instance); // throw an exception if no match
                // create AppScreenshotSet from JS object
                this.actualInstance = AppScreenshotSet.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AppScreenshotSet
            errorMessages.push("Failed to construct AppScreenshotSet: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `AppCustomProductPageLocalizationsResponseIncludedInner` with oneOf schemas AppCustomProductPageVersion, AppKeyword, AppPreviewSet, AppScreenshotSet. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `AppCustomProductPageLocalizationsResponseIncludedInner` with oneOf schemas AppCustomProductPageVersion, AppKeyword, AppPreviewSet, AppScreenshotSet. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>AppCustomProductPageLocalizationsResponseIncludedInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppCustomProductPageLocalizationsResponseIncludedInner} obj Optional instance to populate.
     * @return {module:model/AppCustomProductPageLocalizationsResponseIncludedInner} The populated <code>AppCustomProductPageLocalizationsResponseIncludedInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new AppCustomProductPageLocalizationsResponseIncludedInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>AppCustomProductPageVersion</code>, <code>AppKeyword</code>, <code>AppPreviewSet</code>, <code>AppScreenshotSet</code>.
     * @return {(module:model/AppCustomProductPageVersion|module:model/AppKeyword|module:model/AppPreviewSet|module:model/AppScreenshotSet)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>AppCustomProductPageVersion</code>, <code>AppKeyword</code>, <code>AppPreviewSet</code>, <code>AppScreenshotSet</code>.
     * @param {(module:model/AppCustomProductPageVersion|module:model/AppKeyword|module:model/AppPreviewSet|module:model/AppScreenshotSet)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = AppCustomProductPageLocalizationsResponseIncludedInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of AppCustomProductPageLocalizationsResponseIncludedInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/AppCustomProductPageLocalizationsResponseIncludedInner} An instance of AppCustomProductPageLocalizationsResponseIncludedInner.
     */
    static fromJSON = function(json_string){
        return AppCustomProductPageLocalizationsResponseIncludedInner.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/AppCustomProductPageLocalizationsResponseIncludedInner.TypeEnum} type
 */
AppCustomProductPageLocalizationsResponseIncludedInner.prototype['type'] = undefined;

/**
 * @member {String} id
 */
AppCustomProductPageLocalizationsResponseIncludedInner.prototype['id'] = undefined;

/**
 * @member {module:model/AppScreenshotSetAttributes} attributes
 */
AppCustomProductPageLocalizationsResponseIncludedInner.prototype['attributes'] = undefined;

/**
 * @member {module:model/AppScreenshotSetRelationships} relationships
 */
AppCustomProductPageLocalizationsResponseIncludedInner.prototype['relationships'] = undefined;

/**
 * @member {module:model/ResourceLinks} links
 */
AppCustomProductPageLocalizationsResponseIncludedInner.prototype['links'] = undefined;


AppCustomProductPageLocalizationsResponseIncludedInner.OneOf = ["AppCustomProductPageVersion", "AppKeyword", "AppPreviewSet", "AppScreenshotSet"];

export default AppCustomProductPageLocalizationsResponseIncludedInner;

