/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppClipAdvancedExperienceLocalizationInlineCreateAttributes from './AppClipAdvancedExperienceLocalizationInlineCreateAttributes';

/**
 * The AppClipAdvancedExperienceLocalizationInlineCreate model module.
 * @module model/AppClipAdvancedExperienceLocalizationInlineCreate
 * @version 4.1
 */
class AppClipAdvancedExperienceLocalizationInlineCreate {
    /**
     * Constructs a new <code>AppClipAdvancedExperienceLocalizationInlineCreate</code>.
     * @alias module:model/AppClipAdvancedExperienceLocalizationInlineCreate
     * @param type {module:model/AppClipAdvancedExperienceLocalizationInlineCreate.TypeEnum} 
     */
    constructor(type) { 
        
        AppClipAdvancedExperienceLocalizationInlineCreate.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>AppClipAdvancedExperienceLocalizationInlineCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppClipAdvancedExperienceLocalizationInlineCreate} obj Optional instance to populate.
     * @return {module:model/AppClipAdvancedExperienceLocalizationInlineCreate} The populated <code>AppClipAdvancedExperienceLocalizationInlineCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppClipAdvancedExperienceLocalizationInlineCreate();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = AppClipAdvancedExperienceLocalizationInlineCreateAttributes.constructFromObject(data['attributes']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppClipAdvancedExperienceLocalizationInlineCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppClipAdvancedExperienceLocalizationInlineCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AppClipAdvancedExperienceLocalizationInlineCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          AppClipAdvancedExperienceLocalizationInlineCreateAttributes.validateJSON(data['attributes']);
        }

        return true;
    }


}

AppClipAdvancedExperienceLocalizationInlineCreate.RequiredProperties = ["type"];

/**
 * @member {module:model/AppClipAdvancedExperienceLocalizationInlineCreate.TypeEnum} type
 */
AppClipAdvancedExperienceLocalizationInlineCreate.prototype['type'] = undefined;

/**
 * @member {String} id
 */
AppClipAdvancedExperienceLocalizationInlineCreate.prototype['id'] = undefined;

/**
 * @member {module:model/AppClipAdvancedExperienceLocalizationInlineCreateAttributes} attributes
 */
AppClipAdvancedExperienceLocalizationInlineCreate.prototype['attributes'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
AppClipAdvancedExperienceLocalizationInlineCreate['TypeEnum'] = {

    /**
     * value: "appClipAdvancedExperienceLocalizations"
     * @const
     */
    "appClipAdvancedExperienceLocalizations": "appClipAdvancedExperienceLocalizations"
};



export default AppClipAdvancedExperienceLocalizationInlineCreate;

