/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppCustomProductPageLocalizationCreateRequestDataRelationshipsAppCustomProductPageVersion from './AppCustomProductPageLocalizationCreateRequestDataRelationshipsAppCustomProductPageVersion';

/**
 * The AppCustomProductPageLocalizationCreateRequestDataRelationships model module.
 * @module model/AppCustomProductPageLocalizationCreateRequestDataRelationships
 * @version 4.1
 */
class AppCustomProductPageLocalizationCreateRequestDataRelationships {
    /**
     * Constructs a new <code>AppCustomProductPageLocalizationCreateRequestDataRelationships</code>.
     * @alias module:model/AppCustomProductPageLocalizationCreateRequestDataRelationships
     * @param appCustomProductPageVersion {module:model/AppCustomProductPageLocalizationCreateRequestDataRelationshipsAppCustomProductPageVersion} 
     */
    constructor(appCustomProductPageVersion) { 
        
        AppCustomProductPageLocalizationCreateRequestDataRelationships.initialize(this, appCustomProductPageVersion);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appCustomProductPageVersion) { 
        obj['appCustomProductPageVersion'] = appCustomProductPageVersion;
    }

    /**
     * Constructs a <code>AppCustomProductPageLocalizationCreateRequestDataRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppCustomProductPageLocalizationCreateRequestDataRelationships} obj Optional instance to populate.
     * @return {module:model/AppCustomProductPageLocalizationCreateRequestDataRelationships} The populated <code>AppCustomProductPageLocalizationCreateRequestDataRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppCustomProductPageLocalizationCreateRequestDataRelationships();

            if (data.hasOwnProperty('appCustomProductPageVersion')) {
                obj['appCustomProductPageVersion'] = AppCustomProductPageLocalizationCreateRequestDataRelationshipsAppCustomProductPageVersion.constructFromObject(data['appCustomProductPageVersion']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppCustomProductPageLocalizationCreateRequestDataRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppCustomProductPageLocalizationCreateRequestDataRelationships</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AppCustomProductPageLocalizationCreateRequestDataRelationships.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `appCustomProductPageVersion`
        if (data['appCustomProductPageVersion']) { // data not null
          AppCustomProductPageLocalizationCreateRequestDataRelationshipsAppCustomProductPageVersion.validateJSON(data['appCustomProductPageVersion']);
        }

        return true;
    }


}

AppCustomProductPageLocalizationCreateRequestDataRelationships.RequiredProperties = ["appCustomProductPageVersion"];

/**
 * @member {module:model/AppCustomProductPageLocalizationCreateRequestDataRelationshipsAppCustomProductPageVersion} appCustomProductPageVersion
 */
AppCustomProductPageLocalizationCreateRequestDataRelationships.prototype['appCustomProductPageVersion'] = undefined;






export default AppCustomProductPageLocalizationCreateRequestDataRelationships;

