/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppClipAdvancedExperienceRelationshipsAppClip from './AppClipAdvancedExperienceRelationshipsAppClip';
import AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail from './AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail';
import AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations from './AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations';
import AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion from './AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion';

/**
 * The AppClipDefaultExperienceRelationships model module.
 * @module model/AppClipDefaultExperienceRelationships
 * @version 4.1
 */
class AppClipDefaultExperienceRelationships {
    /**
     * Constructs a new <code>AppClipDefaultExperienceRelationships</code>.
     * @alias module:model/AppClipDefaultExperienceRelationships
     */
    constructor() { 
        
        AppClipDefaultExperienceRelationships.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppClipDefaultExperienceRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppClipDefaultExperienceRelationships} obj Optional instance to populate.
     * @return {module:model/AppClipDefaultExperienceRelationships} The populated <code>AppClipDefaultExperienceRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppClipDefaultExperienceRelationships();

            if (data.hasOwnProperty('appClip')) {
                obj['appClip'] = AppClipAdvancedExperienceRelationshipsAppClip.constructFromObject(data['appClip']);
            }
            if (data.hasOwnProperty('releaseWithAppStoreVersion')) {
                obj['releaseWithAppStoreVersion'] = AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion.constructFromObject(data['releaseWithAppStoreVersion']);
            }
            if (data.hasOwnProperty('appClipDefaultExperienceLocalizations')) {
                obj['appClipDefaultExperienceLocalizations'] = AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations.constructFromObject(data['appClipDefaultExperienceLocalizations']);
            }
            if (data.hasOwnProperty('appClipAppStoreReviewDetail')) {
                obj['appClipAppStoreReviewDetail'] = AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail.constructFromObject(data['appClipAppStoreReviewDetail']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppClipDefaultExperienceRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppClipDefaultExperienceRelationships</code>.
     */
    static validateJSON(data) {
        // validate the optional field `appClip`
        if (data['appClip']) { // data not null
          AppClipAdvancedExperienceRelationshipsAppClip.validateJSON(data['appClip']);
        }
        // validate the optional field `releaseWithAppStoreVersion`
        if (data['releaseWithAppStoreVersion']) { // data not null
          AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion.validateJSON(data['releaseWithAppStoreVersion']);
        }
        // validate the optional field `appClipDefaultExperienceLocalizations`
        if (data['appClipDefaultExperienceLocalizations']) { // data not null
          AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations.validateJSON(data['appClipDefaultExperienceLocalizations']);
        }
        // validate the optional field `appClipAppStoreReviewDetail`
        if (data['appClipAppStoreReviewDetail']) { // data not null
          AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail.validateJSON(data['appClipAppStoreReviewDetail']);
        }

        return true;
    }


}



/**
 * @member {module:model/AppClipAdvancedExperienceRelationshipsAppClip} appClip
 */
AppClipDefaultExperienceRelationships.prototype['appClip'] = undefined;

/**
 * @member {module:model/AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion} releaseWithAppStoreVersion
 */
AppClipDefaultExperienceRelationships.prototype['releaseWithAppStoreVersion'] = undefined;

/**
 * @member {module:model/AppClipDefaultExperienceRelationshipsAppClipDefaultExperienceLocalizations} appClipDefaultExperienceLocalizations
 */
AppClipDefaultExperienceRelationships.prototype['appClipDefaultExperienceLocalizations'] = undefined;

/**
 * @member {module:model/AppClipDefaultExperienceRelationshipsAppClipAppStoreReviewDetail} appClipAppStoreReviewDetail
 */
AppClipDefaultExperienceRelationships.prototype['appClipAppStoreReviewDetail'] = undefined;






export default AppClipDefaultExperienceRelationships;

