/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppClipAction from './AppClipAction';
import AppClipAdvancedExperienceCreateRequestDataAttributesPlace from './AppClipAdvancedExperienceCreateRequestDataAttributesPlace';
import AppClipAdvancedExperienceLanguage from './AppClipAdvancedExperienceLanguage';

/**
 * The AppClipAdvancedExperienceCreateRequestDataAttributes model module.
 * @module model/AppClipAdvancedExperienceCreateRequestDataAttributes
 * @version 4.1
 */
class AppClipAdvancedExperienceCreateRequestDataAttributes {
    /**
     * Constructs a new <code>AppClipAdvancedExperienceCreateRequestDataAttributes</code>.
     * @alias module:model/AppClipAdvancedExperienceCreateRequestDataAttributes
     * @param link {String} 
     * @param isPoweredBy {Boolean} 
     * @param defaultLanguage {module:model/AppClipAdvancedExperienceLanguage} 
     */
    constructor(link, isPoweredBy, defaultLanguage) { 
        
        AppClipAdvancedExperienceCreateRequestDataAttributes.initialize(this, link, isPoweredBy, defaultLanguage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, link, isPoweredBy, defaultLanguage) { 
        obj['link'] = link;
        obj['isPoweredBy'] = isPoweredBy;
        obj['defaultLanguage'] = defaultLanguage;
    }

    /**
     * Constructs a <code>AppClipAdvancedExperienceCreateRequestDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppClipAdvancedExperienceCreateRequestDataAttributes} obj Optional instance to populate.
     * @return {module:model/AppClipAdvancedExperienceCreateRequestDataAttributes} The populated <code>AppClipAdvancedExperienceCreateRequestDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppClipAdvancedExperienceCreateRequestDataAttributes();

            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = AppClipAction.constructFromObject(data['action']);
            }
            if (data.hasOwnProperty('isPoweredBy')) {
                obj['isPoweredBy'] = ApiClient.convertToType(data['isPoweredBy'], 'Boolean');
            }
            if (data.hasOwnProperty('place')) {
                obj['place'] = AppClipAdvancedExperienceCreateRequestDataAttributesPlace.constructFromObject(data['place']);
            }
            if (data.hasOwnProperty('businessCategory')) {
                obj['businessCategory'] = ApiClient.convertToType(data['businessCategory'], 'String');
            }
            if (data.hasOwnProperty('defaultLanguage')) {
                obj['defaultLanguage'] = AppClipAdvancedExperienceLanguage.constructFromObject(data['defaultLanguage']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppClipAdvancedExperienceCreateRequestDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppClipAdvancedExperienceCreateRequestDataAttributes</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AppClipAdvancedExperienceCreateRequestDataAttributes.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['link'] && !(typeof data['link'] === 'string' || data['link'] instanceof String)) {
            throw new Error("Expected the field `link` to be a primitive type in the JSON string but got " + data['link']);
        }
        // validate the optional field `place`
        if (data['place']) { // data not null
          AppClipAdvancedExperienceCreateRequestDataAttributesPlace.validateJSON(data['place']);
        }
        // ensure the json data is a string
        if (data['businessCategory'] && !(typeof data['businessCategory'] === 'string' || data['businessCategory'] instanceof String)) {
            throw new Error("Expected the field `businessCategory` to be a primitive type in the JSON string but got " + data['businessCategory']);
        }

        return true;
    }


}

AppClipAdvancedExperienceCreateRequestDataAttributes.RequiredProperties = ["link", "isPoweredBy", "defaultLanguage"];

/**
 * @member {String} link
 */
AppClipAdvancedExperienceCreateRequestDataAttributes.prototype['link'] = undefined;

/**
 * @member {module:model/AppClipAction} action
 */
AppClipAdvancedExperienceCreateRequestDataAttributes.prototype['action'] = undefined;

/**
 * @member {Boolean} isPoweredBy
 */
AppClipAdvancedExperienceCreateRequestDataAttributes.prototype['isPoweredBy'] = undefined;

/**
 * @member {module:model/AppClipAdvancedExperienceCreateRequestDataAttributesPlace} place
 */
AppClipAdvancedExperienceCreateRequestDataAttributes.prototype['place'] = undefined;

/**
 * @member {module:model/AppClipAdvancedExperienceCreateRequestDataAttributes.BusinessCategoryEnum} businessCategory
 */
AppClipAdvancedExperienceCreateRequestDataAttributes.prototype['businessCategory'] = undefined;

/**
 * @member {module:model/AppClipAdvancedExperienceLanguage} defaultLanguage
 */
AppClipAdvancedExperienceCreateRequestDataAttributes.prototype['defaultLanguage'] = undefined;





/**
 * Allowed values for the <code>businessCategory</code> property.
 * @enum {String}
 * @readonly
 */
AppClipAdvancedExperienceCreateRequestDataAttributes['BusinessCategoryEnum'] = {

    /**
     * value: "AUTOMOTIVE"
     * @const
     */
    "AUTOMOTIVE": "AUTOMOTIVE",

    /**
     * value: "BEAUTY"
     * @const
     */
    "BEAUTY": "BEAUTY",

    /**
     * value: "BIKES"
     * @const
     */
    "BIKES": "BIKES",

    /**
     * value: "BOOKS"
     * @const
     */
    "BOOKS": "BOOKS",

    /**
     * value: "CASINO"
     * @const
     */
    "CASINO": "CASINO",

    /**
     * value: "EDUCATION"
     * @const
     */
    "EDUCATION": "EDUCATION",

    /**
     * value: "EDUCATION_JAPAN"
     * @const
     */
    "EDUCATION_JAPAN": "EDUCATION_JAPAN",

    /**
     * value: "ENTERTAINMENT"
     * @const
     */
    "ENTERTAINMENT": "ENTERTAINMENT",

    /**
     * value: "EV_CHARGER"
     * @const
     */
    "EV_CHARGER": "EV_CHARGER",

    /**
     * value: "FINANCIAL_USD"
     * @const
     */
    "FINANCIAL_USD": "FINANCIAL_USD",

    /**
     * value: "FINANCIAL_CNY"
     * @const
     */
    "FINANCIAL_CNY": "FINANCIAL_CNY",

    /**
     * value: "FINANCIAL_GBP"
     * @const
     */
    "FINANCIAL_GBP": "FINANCIAL_GBP",

    /**
     * value: "FINANCIAL_JPY"
     * @const
     */
    "FINANCIAL_JPY": "FINANCIAL_JPY",

    /**
     * value: "FINANCIAL_EUR"
     * @const
     */
    "FINANCIAL_EUR": "FINANCIAL_EUR",

    /**
     * value: "FITNESS"
     * @const
     */
    "FITNESS": "FITNESS",

    /**
     * value: "FOOD_AND_DRINK"
     * @const
     */
    "FOOD_AND_DRINK": "FOOD_AND_DRINK",

    /**
     * value: "GAS"
     * @const
     */
    "GAS": "GAS",

    /**
     * value: "GROCERY"
     * @const
     */
    "GROCERY": "GROCERY",

    /**
     * value: "HEALTH_AND_MEDICAL"
     * @const
     */
    "HEALTH_AND_MEDICAL": "HEALTH_AND_MEDICAL",

    /**
     * value: "HOTEL_AND_TRAVEL"
     * @const
     */
    "HOTEL_AND_TRAVEL": "HOTEL_AND_TRAVEL",

    /**
     * value: "MUSIC"
     * @const
     */
    "MUSIC": "MUSIC",

    /**
     * value: "PARKING"
     * @const
     */
    "PARKING": "PARKING",

    /**
     * value: "PET_SERVICES"
     * @const
     */
    "PET_SERVICES": "PET_SERVICES",

    /**
     * value: "PROFESSIONAL_SERVICES"
     * @const
     */
    "PROFESSIONAL_SERVICES": "PROFESSIONAL_SERVICES",

    /**
     * value: "SHOPPING"
     * @const
     */
    "SHOPPING": "SHOPPING",

    /**
     * value: "TICKETING"
     * @const
     */
    "TICKETING": "TICKETING",

    /**
     * value: "TRANSIT"
     * @const
     */
    "TRANSIT": "TRANSIT"
};



export default AppClipAdvancedExperienceCreateRequestDataAttributes;

