/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppClipAdvancedExperienceRelationshipsHeaderImageData from './AppClipAdvancedExperienceRelationshipsHeaderImageData';

/**
 * The AppClipAdvancedExperienceRelationshipsHeaderImage model module.
 * @module model/AppClipAdvancedExperienceRelationshipsHeaderImage
 * @version 4.1
 */
class AppClipAdvancedExperienceRelationshipsHeaderImage {
    /**
     * Constructs a new <code>AppClipAdvancedExperienceRelationshipsHeaderImage</code>.
     * @alias module:model/AppClipAdvancedExperienceRelationshipsHeaderImage
     */
    constructor() { 
        
        AppClipAdvancedExperienceRelationshipsHeaderImage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppClipAdvancedExperienceRelationshipsHeaderImage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppClipAdvancedExperienceRelationshipsHeaderImage} obj Optional instance to populate.
     * @return {module:model/AppClipAdvancedExperienceRelationshipsHeaderImage} The populated <code>AppClipAdvancedExperienceRelationshipsHeaderImage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppClipAdvancedExperienceRelationshipsHeaderImage();

            if (data.hasOwnProperty('data')) {
                obj['data'] = AppClipAdvancedExperienceRelationshipsHeaderImageData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppClipAdvancedExperienceRelationshipsHeaderImage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppClipAdvancedExperienceRelationshipsHeaderImage</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          AppClipAdvancedExperienceRelationshipsHeaderImageData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/AppClipAdvancedExperienceRelationshipsHeaderImageData} data
 */
AppClipAdvancedExperienceRelationshipsHeaderImage.prototype['data'] = undefined;






export default AppClipAdvancedExperienceRelationshipsHeaderImage;

