/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AppEncryptionDeclarationCreateRequestDataAttributes model module.
 * @module model/AppEncryptionDeclarationCreateRequestDataAttributes
 * @version 4.1
 */
class AppEncryptionDeclarationCreateRequestDataAttributes {
    /**
     * Constructs a new <code>AppEncryptionDeclarationCreateRequestDataAttributes</code>.
     * @alias module:model/AppEncryptionDeclarationCreateRequestDataAttributes
     * @param appDescription {String} 
     * @param containsProprietaryCryptography {Boolean} 
     * @param containsThirdPartyCryptography {Boolean} 
     * @param availableOnFrenchStore {Boolean} 
     */
    constructor(appDescription, containsProprietaryCryptography, containsThirdPartyCryptography, availableOnFrenchStore) { 
        
        AppEncryptionDeclarationCreateRequestDataAttributes.initialize(this, appDescription, containsProprietaryCryptography, containsThirdPartyCryptography, availableOnFrenchStore);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appDescription, containsProprietaryCryptography, containsThirdPartyCryptography, availableOnFrenchStore) { 
        obj['appDescription'] = appDescription;
        obj['containsProprietaryCryptography'] = containsProprietaryCryptography;
        obj['containsThirdPartyCryptography'] = containsThirdPartyCryptography;
        obj['availableOnFrenchStore'] = availableOnFrenchStore;
    }

    /**
     * Constructs a <code>AppEncryptionDeclarationCreateRequestDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppEncryptionDeclarationCreateRequestDataAttributes} obj Optional instance to populate.
     * @return {module:model/AppEncryptionDeclarationCreateRequestDataAttributes} The populated <code>AppEncryptionDeclarationCreateRequestDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppEncryptionDeclarationCreateRequestDataAttributes();

            if (data.hasOwnProperty('appDescription')) {
                obj['appDescription'] = ApiClient.convertToType(data['appDescription'], 'String');
            }
            if (data.hasOwnProperty('containsProprietaryCryptography')) {
                obj['containsProprietaryCryptography'] = ApiClient.convertToType(data['containsProprietaryCryptography'], 'Boolean');
            }
            if (data.hasOwnProperty('containsThirdPartyCryptography')) {
                obj['containsThirdPartyCryptography'] = ApiClient.convertToType(data['containsThirdPartyCryptography'], 'Boolean');
            }
            if (data.hasOwnProperty('availableOnFrenchStore')) {
                obj['availableOnFrenchStore'] = ApiClient.convertToType(data['availableOnFrenchStore'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppEncryptionDeclarationCreateRequestDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppEncryptionDeclarationCreateRequestDataAttributes</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AppEncryptionDeclarationCreateRequestDataAttributes.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['appDescription'] && !(typeof data['appDescription'] === 'string' || data['appDescription'] instanceof String)) {
            throw new Error("Expected the field `appDescription` to be a primitive type in the JSON string but got " + data['appDescription']);
        }

        return true;
    }


}

AppEncryptionDeclarationCreateRequestDataAttributes.RequiredProperties = ["appDescription", "containsProprietaryCryptography", "containsThirdPartyCryptography", "availableOnFrenchStore"];

/**
 * @member {String} appDescription
 */
AppEncryptionDeclarationCreateRequestDataAttributes.prototype['appDescription'] = undefined;

/**
 * @member {Boolean} containsProprietaryCryptography
 */
AppEncryptionDeclarationCreateRequestDataAttributes.prototype['containsProprietaryCryptography'] = undefined;

/**
 * @member {Boolean} containsThirdPartyCryptography
 */
AppEncryptionDeclarationCreateRequestDataAttributes.prototype['containsThirdPartyCryptography'] = undefined;

/**
 * @member {Boolean} availableOnFrenchStore
 */
AppEncryptionDeclarationCreateRequestDataAttributes.prototype['availableOnFrenchStore'] = undefined;






export default AppEncryptionDeclarationCreateRequestDataAttributes;

