/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppEncryptionDeclarationCreateRequestDataRelationshipsApp from './AppEncryptionDeclarationCreateRequestDataRelationshipsApp';

/**
 * The AppEncryptionDeclarationCreateRequestDataRelationships model module.
 * @module model/AppEncryptionDeclarationCreateRequestDataRelationships
 * @version 4.1
 */
class AppEncryptionDeclarationCreateRequestDataRelationships {
    /**
     * Constructs a new <code>AppEncryptionDeclarationCreateRequestDataRelationships</code>.
     * @alias module:model/AppEncryptionDeclarationCreateRequestDataRelationships
     * @param app {module:model/AppEncryptionDeclarationCreateRequestDataRelationshipsApp} 
     */
    constructor(app) { 
        
        AppEncryptionDeclarationCreateRequestDataRelationships.initialize(this, app);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, app) { 
        obj['app'] = app;
    }

    /**
     * Constructs a <code>AppEncryptionDeclarationCreateRequestDataRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppEncryptionDeclarationCreateRequestDataRelationships} obj Optional instance to populate.
     * @return {module:model/AppEncryptionDeclarationCreateRequestDataRelationships} The populated <code>AppEncryptionDeclarationCreateRequestDataRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppEncryptionDeclarationCreateRequestDataRelationships();

            if (data.hasOwnProperty('app')) {
                obj['app'] = AppEncryptionDeclarationCreateRequestDataRelationshipsApp.constructFromObject(data['app']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppEncryptionDeclarationCreateRequestDataRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppEncryptionDeclarationCreateRequestDataRelationships</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AppEncryptionDeclarationCreateRequestDataRelationships.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `app`
        if (data['app']) { // data not null
          AppEncryptionDeclarationCreateRequestDataRelationshipsApp.validateJSON(data['app']);
        }

        return true;
    }


}

AppEncryptionDeclarationCreateRequestDataRelationships.RequiredProperties = ["app"];

/**
 * @member {module:model/AppEncryptionDeclarationCreateRequestDataRelationshipsApp} app
 */
AppEncryptionDeclarationCreateRequestDataRelationships.prototype['app'] = undefined;






export default AppEncryptionDeclarationCreateRequestDataRelationships;

