/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AppEventScreenshotUpdateRequestDataAttributes model module.
 * @module model/AppEventScreenshotUpdateRequestDataAttributes
 * @version 4.1
 */
class AppEventScreenshotUpdateRequestDataAttributes {
    /**
     * Constructs a new <code>AppEventScreenshotUpdateRequestDataAttributes</code>.
     * @alias module:model/AppEventScreenshotUpdateRequestDataAttributes
     */
    constructor() { 
        
        AppEventScreenshotUpdateRequestDataAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppEventScreenshotUpdateRequestDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppEventScreenshotUpdateRequestDataAttributes} obj Optional instance to populate.
     * @return {module:model/AppEventScreenshotUpdateRequestDataAttributes} The populated <code>AppEventScreenshotUpdateRequestDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppEventScreenshotUpdateRequestDataAttributes();

            if (data.hasOwnProperty('uploaded')) {
                obj['uploaded'] = ApiClient.convertToType(data['uploaded'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppEventScreenshotUpdateRequestDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppEventScreenshotUpdateRequestDataAttributes</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} uploaded
 */
AppEventScreenshotUpdateRequestDataAttributes.prototype['uploaded'] = undefined;






export default AppEventScreenshotUpdateRequestDataAttributes;

