/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AppEventAssetType.
* @enum {}
* @readonly
*/
export default class AppEventAssetType {
    
        /**
         * value: "EVENT_CARD"
         * @const
         */
        "EVENT_CARD" = "EVENT_CARD";

    
        /**
         * value: "EVENT_DETAILS_PAGE"
         * @const
         */
        "EVENT_DETAILS_PAGE" = "EVENT_DETAILS_PAGE";

    

    /**
    * Returns a <code>AppEventAssetType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AppEventAssetType} The enum <code>AppEventAssetType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

