/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AgeRatingDeclaration from './AgeRatingDeclaration';
import App from './App';
import AppAttributes from './AppAttributes';
import AppCategory from './AppCategory';
import AppInfoLocalization from './AppInfoLocalization';
import AppRelationships from './AppRelationships';
import ResourceLinks from './ResourceLinks';

/**
 * The AppInfosResponseIncludedInner model module.
 * @module model/AppInfosResponseIncludedInner
 * @version 4.1
 */
class AppInfosResponseIncludedInner {
    /**
     * Constructs a new <code>AppInfosResponseIncludedInner</code>.
     * @alias module:model/AppInfosResponseIncludedInner
     * @param {(module:model/AgeRatingDeclaration|module:model/App|module:model/AppCategory|module:model/AppInfoLocalization)} instance The actual instance to initialize AppInfosResponseIncludedInner.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "AgeRatingDeclaration") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AgeRatingDeclaration.validateJSON(instance); // throw an exception if no match
                // create AgeRatingDeclaration from JS object
                this.actualInstance = AgeRatingDeclaration.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AgeRatingDeclaration
            errorMessages.push("Failed to construct AgeRatingDeclaration: " + err)
        }

        try {
            if (typeof instance === "AppCategory") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AppCategory.validateJSON(instance); // throw an exception if no match
                // create AppCategory from JS object
                this.actualInstance = AppCategory.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AppCategory
            errorMessages.push("Failed to construct AppCategory: " + err)
        }

        try {
            if (typeof instance === "AppInfoLocalization") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                AppInfoLocalization.validateJSON(instance); // throw an exception if no match
                // create AppInfoLocalization from JS object
                this.actualInstance = AppInfoLocalization.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into AppInfoLocalization
            errorMessages.push("Failed to construct AppInfoLocalization: " + err)
        }

        try {
            if (typeof instance === "App") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                App.validateJSON(instance); // throw an exception if no match
                // create App from JS object
                this.actualInstance = App.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into App
            errorMessages.push("Failed to construct App: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `AppInfosResponseIncludedInner` with oneOf schemas AgeRatingDeclaration, App, AppCategory, AppInfoLocalization. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `AppInfosResponseIncludedInner` with oneOf schemas AgeRatingDeclaration, App, AppCategory, AppInfoLocalization. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>AppInfosResponseIncludedInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppInfosResponseIncludedInner} obj Optional instance to populate.
     * @return {module:model/AppInfosResponseIncludedInner} The populated <code>AppInfosResponseIncludedInner</code> instance.
     */
    static constructFromObject(data, obj) {
        return new AppInfosResponseIncludedInner(data);
    }

    /**
     * Gets the actual instance, which can be <code>AgeRatingDeclaration</code>, <code>App</code>, <code>AppCategory</code>, <code>AppInfoLocalization</code>.
     * @return {(module:model/AgeRatingDeclaration|module:model/App|module:model/AppCategory|module:model/AppInfoLocalization)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>AgeRatingDeclaration</code>, <code>App</code>, <code>AppCategory</code>, <code>AppInfoLocalization</code>.
     * @param {(module:model/AgeRatingDeclaration|module:model/App|module:model/AppCategory|module:model/AppInfoLocalization)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = AppInfosResponseIncludedInner.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of AppInfosResponseIncludedInner from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/AppInfosResponseIncludedInner} An instance of AppInfosResponseIncludedInner.
     */
    static fromJSON = function(json_string){
        return AppInfosResponseIncludedInner.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {module:model/AppInfosResponseIncludedInner.TypeEnum} type
 */
AppInfosResponseIncludedInner.prototype['type'] = undefined;

/**
 * @member {String} id
 */
AppInfosResponseIncludedInner.prototype['id'] = undefined;

/**
 * @member {module:model/AppAttributes} attributes
 */
AppInfosResponseIncludedInner.prototype['attributes'] = undefined;

/**
 * @member {module:model/ResourceLinks} links
 */
AppInfosResponseIncludedInner.prototype['links'] = undefined;

/**
 * @member {module:model/AppRelationships} relationships
 */
AppInfosResponseIncludedInner.prototype['relationships'] = undefined;


AppInfosResponseIncludedInner.OneOf = ["AgeRatingDeclaration", "App", "AppCategory", "AppInfoLocalization"];

export default AppInfosResponseIncludedInner;

