/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppRelationshipsGameCenterDetailData from './AppRelationshipsGameCenterDetailData';
import RelationshipLinks from './RelationshipLinks';

/**
 * The AppRelationshipsGameCenterDetail model module.
 * @module model/AppRelationshipsGameCenterDetail
 * @version 4.1
 */
class AppRelationshipsGameCenterDetail {
    /**
     * Constructs a new <code>AppRelationshipsGameCenterDetail</code>.
     * @alias module:model/AppRelationshipsGameCenterDetail
     */
    constructor() { 
        
        AppRelationshipsGameCenterDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppRelationshipsGameCenterDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppRelationshipsGameCenterDetail} obj Optional instance to populate.
     * @return {module:model/AppRelationshipsGameCenterDetail} The populated <code>AppRelationshipsGameCenterDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppRelationshipsGameCenterDetail();

            if (data.hasOwnProperty('links')) {
                obj['links'] = RelationshipLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = AppRelationshipsGameCenterDetailData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppRelationshipsGameCenterDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppRelationshipsGameCenterDetail</code>.
     */
    static validateJSON(data) {
        // validate the optional field `links`
        if (data['links']) { // data not null
          RelationshipLinks.validateJSON(data['links']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          AppRelationshipsGameCenterDetailData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/RelationshipLinks} links
 */
AppRelationshipsGameCenterDetail.prototype['links'] = undefined;

/**
 * @member {module:model/AppRelationshipsGameCenterDetailData} data
 */
AppRelationshipsGameCenterDetail.prototype['data'] = undefined;






export default AppRelationshipsGameCenterDetail;

