/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppStoreVersionRelationshipsAppStoreVersionSubmissionData from './AppStoreVersionRelationshipsAppStoreVersionSubmissionData';
import DocumentLinks from './DocumentLinks';

/**
 * The AppStoreVersionAppStoreVersionSubmissionLinkageResponse model module.
 * @module model/AppStoreVersionAppStoreVersionSubmissionLinkageResponse
 * @version 4.1
 */
class AppStoreVersionAppStoreVersionSubmissionLinkageResponse {
    /**
     * Constructs a new <code>AppStoreVersionAppStoreVersionSubmissionLinkageResponse</code>.
     * @alias module:model/AppStoreVersionAppStoreVersionSubmissionLinkageResponse
     * @param data {module:model/AppStoreVersionRelationshipsAppStoreVersionSubmissionData} 
     * @param links {module:model/DocumentLinks} 
     */
    constructor(data, links) { 
        
        AppStoreVersionAppStoreVersionSubmissionLinkageResponse.initialize(this, data, links);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data, links) { 
        obj['data'] = data;
        obj['links'] = links;
    }

    /**
     * Constructs a <code>AppStoreVersionAppStoreVersionSubmissionLinkageResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppStoreVersionAppStoreVersionSubmissionLinkageResponse} obj Optional instance to populate.
     * @return {module:model/AppStoreVersionAppStoreVersionSubmissionLinkageResponse} The populated <code>AppStoreVersionAppStoreVersionSubmissionLinkageResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppStoreVersionAppStoreVersionSubmissionLinkageResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = AppStoreVersionRelationshipsAppStoreVersionSubmissionData.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = DocumentLinks.constructFromObject(data['links']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppStoreVersionAppStoreVersionSubmissionLinkageResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppStoreVersionAppStoreVersionSubmissionLinkageResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AppStoreVersionAppStoreVersionSubmissionLinkageResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          AppStoreVersionRelationshipsAppStoreVersionSubmissionData.validateJSON(data['data']);
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          DocumentLinks.validateJSON(data['links']);
        }

        return true;
    }


}

AppStoreVersionAppStoreVersionSubmissionLinkageResponse.RequiredProperties = ["data", "links"];

/**
 * @member {module:model/AppStoreVersionRelationshipsAppStoreVersionSubmissionData} data
 */
AppStoreVersionAppStoreVersionSubmissionLinkageResponse.prototype['data'] = undefined;

/**
 * @member {module:model/DocumentLinks} links
 */
AppStoreVersionAppStoreVersionSubmissionLinkageResponse.prototype['links'] = undefined;






export default AppStoreVersionAppStoreVersionSubmissionLinkageResponse;

