/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppStoreVersionState from './AppStoreVersionState';
import AppVersionState from './AppVersionState';
import Platform from './Platform';

/**
 * The AppStoreVersionAttributes model module.
 * @module model/AppStoreVersionAttributes
 * @version 4.1
 */
class AppStoreVersionAttributes {
    /**
     * Constructs a new <code>AppStoreVersionAttributes</code>.
     * @alias module:model/AppStoreVersionAttributes
     */
    constructor() { 
        
        AppStoreVersionAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppStoreVersionAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppStoreVersionAttributes} obj Optional instance to populate.
     * @return {module:model/AppStoreVersionAttributes} The populated <code>AppStoreVersionAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppStoreVersionAttributes();

            if (data.hasOwnProperty('platform')) {
                obj['platform'] = Platform.constructFromObject(data['platform']);
            }
            if (data.hasOwnProperty('versionString')) {
                obj['versionString'] = ApiClient.convertToType(data['versionString'], 'String');
            }
            if (data.hasOwnProperty('appStoreState')) {
                obj['appStoreState'] = AppStoreVersionState.constructFromObject(data['appStoreState']);
            }
            if (data.hasOwnProperty('appVersionState')) {
                obj['appVersionState'] = AppVersionState.constructFromObject(data['appVersionState']);
            }
            if (data.hasOwnProperty('copyright')) {
                obj['copyright'] = ApiClient.convertToType(data['copyright'], 'String');
            }
            if (data.hasOwnProperty('reviewType')) {
                obj['reviewType'] = ApiClient.convertToType(data['reviewType'], 'String');
            }
            if (data.hasOwnProperty('releaseType')) {
                obj['releaseType'] = ApiClient.convertToType(data['releaseType'], 'String');
            }
            if (data.hasOwnProperty('earliestReleaseDate')) {
                obj['earliestReleaseDate'] = ApiClient.convertToType(data['earliestReleaseDate'], 'Date');
            }
            if (data.hasOwnProperty('usesIdfa')) {
                obj['usesIdfa'] = ApiClient.convertToType(data['usesIdfa'], 'Boolean');
            }
            if (data.hasOwnProperty('downloadable')) {
                obj['downloadable'] = ApiClient.convertToType(data['downloadable'], 'Boolean');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppStoreVersionAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppStoreVersionAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['versionString'] && !(typeof data['versionString'] === 'string' || data['versionString'] instanceof String)) {
            throw new Error("Expected the field `versionString` to be a primitive type in the JSON string but got " + data['versionString']);
        }
        // ensure the json data is a string
        if (data['copyright'] && !(typeof data['copyright'] === 'string' || data['copyright'] instanceof String)) {
            throw new Error("Expected the field `copyright` to be a primitive type in the JSON string but got " + data['copyright']);
        }
        // ensure the json data is a string
        if (data['reviewType'] && !(typeof data['reviewType'] === 'string' || data['reviewType'] instanceof String)) {
            throw new Error("Expected the field `reviewType` to be a primitive type in the JSON string but got " + data['reviewType']);
        }
        // ensure the json data is a string
        if (data['releaseType'] && !(typeof data['releaseType'] === 'string' || data['releaseType'] instanceof String)) {
            throw new Error("Expected the field `releaseType` to be a primitive type in the JSON string but got " + data['releaseType']);
        }

        return true;
    }


}



/**
 * @member {module:model/Platform} platform
 */
AppStoreVersionAttributes.prototype['platform'] = undefined;

/**
 * @member {String} versionString
 */
AppStoreVersionAttributes.prototype['versionString'] = undefined;

/**
 * @member {module:model/AppStoreVersionState} appStoreState
 */
AppStoreVersionAttributes.prototype['appStoreState'] = undefined;

/**
 * @member {module:model/AppVersionState} appVersionState
 */
AppStoreVersionAttributes.prototype['appVersionState'] = undefined;

/**
 * @member {String} copyright
 */
AppStoreVersionAttributes.prototype['copyright'] = undefined;

/**
 * @member {module:model/AppStoreVersionAttributes.ReviewTypeEnum} reviewType
 */
AppStoreVersionAttributes.prototype['reviewType'] = undefined;

/**
 * @member {module:model/AppStoreVersionAttributes.ReleaseTypeEnum} releaseType
 */
AppStoreVersionAttributes.prototype['releaseType'] = undefined;

/**
 * @member {Date} earliestReleaseDate
 */
AppStoreVersionAttributes.prototype['earliestReleaseDate'] = undefined;

/**
 * @member {Boolean} usesIdfa
 */
AppStoreVersionAttributes.prototype['usesIdfa'] = undefined;

/**
 * @member {Boolean} downloadable
 */
AppStoreVersionAttributes.prototype['downloadable'] = undefined;

/**
 * @member {Date} createdDate
 */
AppStoreVersionAttributes.prototype['createdDate'] = undefined;





/**
 * Allowed values for the <code>reviewType</code> property.
 * @enum {String}
 * @readonly
 */
AppStoreVersionAttributes['ReviewTypeEnum'] = {

    /**
     * value: "APP_STORE"
     * @const
     */
    "APP_STORE": "APP_STORE",

    /**
     * value: "NOTARIZATION"
     * @const
     */
    "NOTARIZATION": "NOTARIZATION"
};


/**
 * Allowed values for the <code>releaseType</code> property.
 * @enum {String}
 * @readonly
 */
AppStoreVersionAttributes['ReleaseTypeEnum'] = {

    /**
     * value: "MANUAL"
     * @const
     */
    "MANUAL": "MANUAL",

    /**
     * value: "AFTER_APPROVAL"
     * @const
     */
    "AFTER_APPROVAL": "AFTER_APPROVAL",

    /**
     * value: "SCHEDULED"
     * @const
     */
    "SCHEDULED": "SCHEDULED"
};



export default AppStoreVersionAttributes;

