/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion from './AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion';
import AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments from './AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments';

/**
 * The AppStoreVersionExperimentRelationships model module.
 * @module model/AppStoreVersionExperimentRelationships
 * @version 4.1
 */
class AppStoreVersionExperimentRelationships {
    /**
     * Constructs a new <code>AppStoreVersionExperimentRelationships</code>.
     * @alias module:model/AppStoreVersionExperimentRelationships
     */
    constructor() { 
        
        AppStoreVersionExperimentRelationships.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AppStoreVersionExperimentRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AppStoreVersionExperimentRelationships} obj Optional instance to populate.
     * @return {module:model/AppStoreVersionExperimentRelationships} The populated <code>AppStoreVersionExperimentRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AppStoreVersionExperimentRelationships();

            if (data.hasOwnProperty('appStoreVersion')) {
                obj['appStoreVersion'] = AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion.constructFromObject(data['appStoreVersion']);
            }
            if (data.hasOwnProperty('appStoreVersionExperimentTreatments')) {
                obj['appStoreVersionExperimentTreatments'] = AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments.constructFromObject(data['appStoreVersionExperimentTreatments']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AppStoreVersionExperimentRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AppStoreVersionExperimentRelationships</code>.
     */
    static validateJSON(data) {
        // validate the optional field `appStoreVersion`
        if (data['appStoreVersion']) { // data not null
          AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion.validateJSON(data['appStoreVersion']);
        }
        // validate the optional field `appStoreVersionExperimentTreatments`
        if (data['appStoreVersionExperimentTreatments']) { // data not null
          AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments.validateJSON(data['appStoreVersionExperimentTreatments']);
        }

        return true;
    }


}



/**
 * @member {module:model/AppClipDefaultExperienceCreateRequestDataRelationshipsReleaseWithAppStoreVersion} appStoreVersion
 */
AppStoreVersionExperimentRelationships.prototype['appStoreVersion'] = undefined;

/**
 * @member {module:model/AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments} appStoreVersionExperimentTreatments
 */
AppStoreVersionExperimentRelationships.prototype['appStoreVersionExperimentTreatments'] = undefined;






export default AppStoreVersionExperimentRelationships;

