/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints from './AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints';
import BetaTesterUsagesV1MetricResponseDataInnerDimensions from './BetaTesterUsagesV1MetricResponseDataInnerDimensions';

/**
 * The BetaTesterUsagesV1MetricResponseDataInner model module.
 * @module model/BetaTesterUsagesV1MetricResponseDataInner
 * @version 4.1
 */
class BetaTesterUsagesV1MetricResponseDataInner {
    /**
     * Constructs a new <code>BetaTesterUsagesV1MetricResponseDataInner</code>.
     * @alias module:model/BetaTesterUsagesV1MetricResponseDataInner
     */
    constructor() { 
        
        BetaTesterUsagesV1MetricResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BetaTesterUsagesV1MetricResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BetaTesterUsagesV1MetricResponseDataInner} obj Optional instance to populate.
     * @return {module:model/BetaTesterUsagesV1MetricResponseDataInner} The populated <code>BetaTesterUsagesV1MetricResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BetaTesterUsagesV1MetricResponseDataInner();

            if (data.hasOwnProperty('dataPoints')) {
                obj['dataPoints'] = AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints.constructFromObject(data['dataPoints']);
            }
            if (data.hasOwnProperty('dimensions')) {
                obj['dimensions'] = BetaTesterUsagesV1MetricResponseDataInnerDimensions.constructFromObject(data['dimensions']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BetaTesterUsagesV1MetricResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BetaTesterUsagesV1MetricResponseDataInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `dataPoints`
        if (data['dataPoints']) { // data not null
          AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints.validateJSON(data['dataPoints']);
        }
        // validate the optional field `dimensions`
        if (data['dimensions']) { // data not null
          BetaTesterUsagesV1MetricResponseDataInnerDimensions.validateJSON(data['dimensions']);
        }

        return true;
    }


}



/**
 * @member {module:model/AppsBetaTesterUsagesV1MetricResponseDataInnerDataPoints} dataPoints
 */
BetaTesterUsagesV1MetricResponseDataInner.prototype['dataPoints'] = undefined;

/**
 * @member {module:model/BetaTesterUsagesV1MetricResponseDataInnerDimensions} dimensions
 */
BetaTesterUsagesV1MetricResponseDataInner.prototype['dimensions'] = undefined;






export default BetaTesterUsagesV1MetricResponseDataInner;

