/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues model module.
 * @module model/BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
 * @version 4.1
 */
class BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues {
    /**
     * Constructs a new <code>BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues</code>.
     * @alias module:model/BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
     */
    constructor() { 
        
        BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues} obj Optional instance to populate.
     * @return {module:model/BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues} The populated <code>BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues();

            if (data.hasOwnProperty('viewCount')) {
                obj['viewCount'] = ApiClient.convertToType(data['viewCount'], 'Number');
            }
            if (data.hasOwnProperty('acceptedCount')) {
                obj['acceptedCount'] = ApiClient.convertToType(data['acceptedCount'], 'Number');
            }
            if (data.hasOwnProperty('didNotAcceptCount')) {
                obj['didNotAcceptCount'] = ApiClient.convertToType(data['didNotAcceptCount'], 'Number');
            }
            if (data.hasOwnProperty('didNotMeetCriteriaCount')) {
                obj['didNotMeetCriteriaCount'] = ApiClient.convertToType(data['didNotMeetCriteriaCount'], 'Number');
            }
            if (data.hasOwnProperty('notRelevantRatio')) {
                obj['notRelevantRatio'] = ApiClient.convertToType(data['notRelevantRatio'], 'Number');
            }
            if (data.hasOwnProperty('notClearRatio')) {
                obj['notClearRatio'] = ApiClient.convertToType(data['notClearRatio'], 'Number');
            }
            if (data.hasOwnProperty('notInterestingRatio')) {
                obj['notInterestingRatio'] = ApiClient.convertToType(data['notInterestingRatio'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} viewCount
 */
BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues.prototype['viewCount'] = undefined;

/**
 * @member {Number} acceptedCount
 */
BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues.prototype['acceptedCount'] = undefined;

/**
 * @member {Number} didNotAcceptCount
 */
BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues.prototype['didNotAcceptCount'] = undefined;

/**
 * @member {Number} didNotMeetCriteriaCount
 */
BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues.prototype['didNotMeetCriteriaCount'] = undefined;

/**
 * @member {Number} notRelevantRatio
 */
BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues.prototype['notRelevantRatio'] = undefined;

/**
 * @member {Number} notClearRatio
 */
BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues.prototype['notClearRatio'] = undefined;

/**
 * @member {Number} notInterestingRatio
 */
BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues.prototype['notInterestingRatio'] = undefined;






export default BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues;

