/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CiBuildActionRelationshipsBuildRunData from './CiBuildActionRelationshipsBuildRunData';

/**
 * The CiBuildRunCreateRequestDataRelationshipsBuildRun model module.
 * @module model/CiBuildRunCreateRequestDataRelationshipsBuildRun
 * @version 4.1
 */
class CiBuildRunCreateRequestDataRelationshipsBuildRun {
    /**
     * Constructs a new <code>CiBuildRunCreateRequestDataRelationshipsBuildRun</code>.
     * @alias module:model/CiBuildRunCreateRequestDataRelationshipsBuildRun
     */
    constructor() { 
        
        CiBuildRunCreateRequestDataRelationshipsBuildRun.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CiBuildRunCreateRequestDataRelationshipsBuildRun</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CiBuildRunCreateRequestDataRelationshipsBuildRun} obj Optional instance to populate.
     * @return {module:model/CiBuildRunCreateRequestDataRelationshipsBuildRun} The populated <code>CiBuildRunCreateRequestDataRelationshipsBuildRun</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CiBuildRunCreateRequestDataRelationshipsBuildRun();

            if (data.hasOwnProperty('data')) {
                obj['data'] = CiBuildActionRelationshipsBuildRunData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CiBuildRunCreateRequestDataRelationshipsBuildRun</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CiBuildRunCreateRequestDataRelationshipsBuildRun</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          CiBuildActionRelationshipsBuildRunData.validateJSON(data['data']);
        }

        return true;
    }


}



/**
 * @member {module:model/CiBuildActionRelationshipsBuildRunData} data
 */
CiBuildRunCreateRequestDataRelationshipsBuildRun.prototype['data'] = undefined;






export default CiBuildRunCreateRequestDataRelationshipsBuildRun;

