/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CiTagPatterns from './CiTagPatterns';

/**
 * The CiManualTagStartCondition model module.
 * @module model/CiManualTagStartCondition
 * @version 4.1
 */
class CiManualTagStartCondition {
    /**
     * Constructs a new <code>CiManualTagStartCondition</code>.
     * @alias module:model/CiManualTagStartCondition
     */
    constructor() { 
        
        CiManualTagStartCondition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CiManualTagStartCondition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CiManualTagStartCondition} obj Optional instance to populate.
     * @return {module:model/CiManualTagStartCondition} The populated <code>CiManualTagStartCondition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CiManualTagStartCondition();

            if (data.hasOwnProperty('source')) {
                obj['source'] = CiTagPatterns.constructFromObject(data['source']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CiManualTagStartCondition</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CiManualTagStartCondition</code>.
     */
    static validateJSON(data) {
        // validate the optional field `source`
        if (data['source']) { // data not null
          CiTagPatterns.validateJSON(data['source']);
        }

        return true;
    }


}



/**
 * @member {module:model/CiTagPatterns} source
 */
CiManualTagStartCondition.prototype['source'] = undefined;






export default CiManualTagStartCondition;

