/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CiAction from './CiAction';
import CiBranchStartCondition from './CiBranchStartCondition';
import CiManualBranchStartCondition from './CiManualBranchStartCondition';
import CiManualPullRequestStartCondition from './CiManualPullRequestStartCondition';
import CiManualTagStartCondition from './CiManualTagStartCondition';
import CiPullRequestStartCondition from './CiPullRequestStartCondition';
import CiScheduledStartCondition from './CiScheduledStartCondition';
import CiTagStartCondition from './CiTagStartCondition';

/**
 * The CiWorkflowCreateRequestDataAttributes model module.
 * @module model/CiWorkflowCreateRequestDataAttributes
 * @version 4.1
 */
class CiWorkflowCreateRequestDataAttributes {
    /**
     * Constructs a new <code>CiWorkflowCreateRequestDataAttributes</code>.
     * @alias module:model/CiWorkflowCreateRequestDataAttributes
     * @param name {String} 
     * @param description {String} 
     * @param actions {Array.<module:model/CiAction>} 
     * @param isEnabled {Boolean} 
     * @param clean {Boolean} 
     * @param containerFilePath {String} 
     */
    constructor(name, description, actions, isEnabled, clean, containerFilePath) { 
        
        CiWorkflowCreateRequestDataAttributes.initialize(this, name, description, actions, isEnabled, clean, containerFilePath);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description, actions, isEnabled, clean, containerFilePath) { 
        obj['name'] = name;
        obj['description'] = description;
        obj['actions'] = actions;
        obj['isEnabled'] = isEnabled;
        obj['clean'] = clean;
        obj['containerFilePath'] = containerFilePath;
    }

    /**
     * Constructs a <code>CiWorkflowCreateRequestDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CiWorkflowCreateRequestDataAttributes} obj Optional instance to populate.
     * @return {module:model/CiWorkflowCreateRequestDataAttributes} The populated <code>CiWorkflowCreateRequestDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CiWorkflowCreateRequestDataAttributes();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('branchStartCondition')) {
                obj['branchStartCondition'] = CiBranchStartCondition.constructFromObject(data['branchStartCondition']);
            }
            if (data.hasOwnProperty('tagStartCondition')) {
                obj['tagStartCondition'] = CiTagStartCondition.constructFromObject(data['tagStartCondition']);
            }
            if (data.hasOwnProperty('pullRequestStartCondition')) {
                obj['pullRequestStartCondition'] = CiPullRequestStartCondition.constructFromObject(data['pullRequestStartCondition']);
            }
            if (data.hasOwnProperty('scheduledStartCondition')) {
                obj['scheduledStartCondition'] = CiScheduledStartCondition.constructFromObject(data['scheduledStartCondition']);
            }
            if (data.hasOwnProperty('manualBranchStartCondition')) {
                obj['manualBranchStartCondition'] = CiManualBranchStartCondition.constructFromObject(data['manualBranchStartCondition']);
            }
            if (data.hasOwnProperty('manualTagStartCondition')) {
                obj['manualTagStartCondition'] = CiManualTagStartCondition.constructFromObject(data['manualTagStartCondition']);
            }
            if (data.hasOwnProperty('manualPullRequestStartCondition')) {
                obj['manualPullRequestStartCondition'] = CiManualPullRequestStartCondition.constructFromObject(data['manualPullRequestStartCondition']);
            }
            if (data.hasOwnProperty('actions')) {
                obj['actions'] = ApiClient.convertToType(data['actions'], [CiAction]);
            }
            if (data.hasOwnProperty('isEnabled')) {
                obj['isEnabled'] = ApiClient.convertToType(data['isEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('isLockedForEditing')) {
                obj['isLockedForEditing'] = ApiClient.convertToType(data['isLockedForEditing'], 'Boolean');
            }
            if (data.hasOwnProperty('clean')) {
                obj['clean'] = ApiClient.convertToType(data['clean'], 'Boolean');
            }
            if (data.hasOwnProperty('containerFilePath')) {
                obj['containerFilePath'] = ApiClient.convertToType(data['containerFilePath'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CiWorkflowCreateRequestDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CiWorkflowCreateRequestDataAttributes</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CiWorkflowCreateRequestDataAttributes.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // validate the optional field `branchStartCondition`
        if (data['branchStartCondition']) { // data not null
          CiBranchStartCondition.validateJSON(data['branchStartCondition']);
        }
        // validate the optional field `tagStartCondition`
        if (data['tagStartCondition']) { // data not null
          CiTagStartCondition.validateJSON(data['tagStartCondition']);
        }
        // validate the optional field `pullRequestStartCondition`
        if (data['pullRequestStartCondition']) { // data not null
          CiPullRequestStartCondition.validateJSON(data['pullRequestStartCondition']);
        }
        // validate the optional field `scheduledStartCondition`
        if (data['scheduledStartCondition']) { // data not null
          CiScheduledStartCondition.validateJSON(data['scheduledStartCondition']);
        }
        // validate the optional field `manualBranchStartCondition`
        if (data['manualBranchStartCondition']) { // data not null
          CiManualBranchStartCondition.validateJSON(data['manualBranchStartCondition']);
        }
        // validate the optional field `manualTagStartCondition`
        if (data['manualTagStartCondition']) { // data not null
          CiManualTagStartCondition.validateJSON(data['manualTagStartCondition']);
        }
        // validate the optional field `manualPullRequestStartCondition`
        if (data['manualPullRequestStartCondition']) { // data not null
          CiManualPullRequestStartCondition.validateJSON(data['manualPullRequestStartCondition']);
        }
        if (data['actions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['actions'])) {
                throw new Error("Expected the field `actions` to be an array in the JSON data but got " + data['actions']);
            }
            // validate the optional field `actions` (array)
            for (const item of data['actions']) {
                CiAction.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['containerFilePath'] && !(typeof data['containerFilePath'] === 'string' || data['containerFilePath'] instanceof String)) {
            throw new Error("Expected the field `containerFilePath` to be a primitive type in the JSON string but got " + data['containerFilePath']);
        }

        return true;
    }


}

CiWorkflowCreateRequestDataAttributes.RequiredProperties = ["name", "description", "actions", "isEnabled", "clean", "containerFilePath"];

/**
 * @member {String} name
 */
CiWorkflowCreateRequestDataAttributes.prototype['name'] = undefined;

/**
 * @member {String} description
 */
CiWorkflowCreateRequestDataAttributes.prototype['description'] = undefined;

/**
 * @member {module:model/CiBranchStartCondition} branchStartCondition
 */
CiWorkflowCreateRequestDataAttributes.prototype['branchStartCondition'] = undefined;

/**
 * @member {module:model/CiTagStartCondition} tagStartCondition
 */
CiWorkflowCreateRequestDataAttributes.prototype['tagStartCondition'] = undefined;

/**
 * @member {module:model/CiPullRequestStartCondition} pullRequestStartCondition
 */
CiWorkflowCreateRequestDataAttributes.prototype['pullRequestStartCondition'] = undefined;

/**
 * @member {module:model/CiScheduledStartCondition} scheduledStartCondition
 */
CiWorkflowCreateRequestDataAttributes.prototype['scheduledStartCondition'] = undefined;

/**
 * @member {module:model/CiManualBranchStartCondition} manualBranchStartCondition
 */
CiWorkflowCreateRequestDataAttributes.prototype['manualBranchStartCondition'] = undefined;

/**
 * @member {module:model/CiManualTagStartCondition} manualTagStartCondition
 */
CiWorkflowCreateRequestDataAttributes.prototype['manualTagStartCondition'] = undefined;

/**
 * @member {module:model/CiManualPullRequestStartCondition} manualPullRequestStartCondition
 */
CiWorkflowCreateRequestDataAttributes.prototype['manualPullRequestStartCondition'] = undefined;

/**
 * @member {Array.<module:model/CiAction>} actions
 */
CiWorkflowCreateRequestDataAttributes.prototype['actions'] = undefined;

/**
 * @member {Boolean} isEnabled
 */
CiWorkflowCreateRequestDataAttributes.prototype['isEnabled'] = undefined;

/**
 * @member {Boolean} isLockedForEditing
 */
CiWorkflowCreateRequestDataAttributes.prototype['isLockedForEditing'] = undefined;

/**
 * @member {Boolean} clean
 */
CiWorkflowCreateRequestDataAttributes.prototype['clean'] = undefined;

/**
 * @member {String} containerFilePath
 */
CiWorkflowCreateRequestDataAttributes.prototype['containerFilePath'] = undefined;






export default CiWorkflowCreateRequestDataAttributes;

