/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DeviceFamily.
* @enum {}
* @readonly
*/
export default class DeviceFamily {
    
        /**
         * value: "IPHONE"
         * @const
         */
        "IPHONE" = "IPHONE";

    
        /**
         * value: "IPAD"
         * @const
         */
        "IPAD" = "IPAD";

    
        /**
         * value: "APPLE_TV"
         * @const
         */
        "APPLE_TV" = "APPLE_TV";

    
        /**
         * value: "APPLE_WATCH"
         * @const
         */
        "APPLE_WATCH" = "APPLE_WATCH";

    
        /**
         * value: "MAC"
         * @const
         */
        "MAC" = "MAC";

    
        /**
         * value: "VISION"
         * @const
         */
        "VISION" = "VISION";

    

    /**
    * Returns a <code>DeviceFamily</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DeviceFamily} The enum <code>DeviceFamily</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

