/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DiagnosticLogsProductDataInner from './DiagnosticLogsProductDataInner';

/**
 * The DiagnosticLogs model module.
 * @module model/DiagnosticLogs
 * @version 4.1
 */
class DiagnosticLogs {
    /**
     * Constructs a new <code>DiagnosticLogs</code>.
     * @alias module:model/DiagnosticLogs
     */
    constructor() { 
        
        DiagnosticLogs.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DiagnosticLogs</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DiagnosticLogs} obj Optional instance to populate.
     * @return {module:model/DiagnosticLogs} The populated <code>DiagnosticLogs</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DiagnosticLogs();

            if (data.hasOwnProperty('productData')) {
                obj['productData'] = ApiClient.convertToType(data['productData'], [DiagnosticLogsProductDataInner]);
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DiagnosticLogs</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DiagnosticLogs</code>.
     */
    static validateJSON(data) {
        if (data['productData']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['productData'])) {
                throw new Error("Expected the field `productData` to be an array in the JSON data but got " + data['productData']);
            }
            // validate the optional field `productData` (array)
            for (const item of data['productData']) {
                DiagnosticLogsProductDataInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/DiagnosticLogsProductDataInner>} productData
 */
DiagnosticLogs.prototype['productData'] = undefined;

/**
 * @member {String} version
 */
DiagnosticLogs.prototype['version'] = undefined;






export default DiagnosticLogs;

