/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GameCenterChallenge from './GameCenterChallenge';
import GameCenterChallengesResponseIncludedInner from './GameCenterChallengesResponseIncludedInner';
import PagedDocumentLinks from './PagedDocumentLinks';
import PagingInformation from './PagingInformation';

/**
 * The GameCenterChallengesResponse model module.
 * @module model/GameCenterChallengesResponse
 * @version 4.1
 */
class GameCenterChallengesResponse {
    /**
     * Constructs a new <code>GameCenterChallengesResponse</code>.
     * @alias module:model/GameCenterChallengesResponse
     * @param data {Array.<module:model/GameCenterChallenge>} 
     * @param links {module:model/PagedDocumentLinks} 
     */
    constructor(data, links) { 
        
        GameCenterChallengesResponse.initialize(this, data, links);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data, links) { 
        obj['data'] = data;
        obj['links'] = links;
    }

    /**
     * Constructs a <code>GameCenterChallengesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterChallengesResponse} obj Optional instance to populate.
     * @return {module:model/GameCenterChallengesResponse} The populated <code>GameCenterChallengesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterChallengesResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [GameCenterChallenge]);
            }
            if (data.hasOwnProperty('included')) {
                obj['included'] = ApiClient.convertToType(data['included'], [GameCenterChallengesResponseIncludedInner]);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = PagedDocumentLinks.constructFromObject(data['links']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = PagingInformation.constructFromObject(data['meta']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterChallengesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterChallengesResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GameCenterChallengesResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                GameCenterChallenge.validateJSON(item);
            };
        }
        if (data['included']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['included'])) {
                throw new Error("Expected the field `included` to be an array in the JSON data but got " + data['included']);
            }
            // validate the optional field `included` (array)
            for (const item of data['included']) {
                GameCenterChallengesResponseIncludedInner.validateJSON(item);
            };
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          PagedDocumentLinks.validateJSON(data['links']);
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          PagingInformation.validateJSON(data['meta']);
        }

        return true;
    }


}

GameCenterChallengesResponse.RequiredProperties = ["data", "links"];

/**
 * @member {Array.<module:model/GameCenterChallenge>} data
 */
GameCenterChallengesResponse.prototype['data'] = undefined;

/**
 * @member {Array.<module:model/GameCenterChallengesResponseIncludedInner>} included
 */
GameCenterChallengesResponse.prototype['included'] = undefined;

/**
 * @member {module:model/PagedDocumentLinks} links
 */
GameCenterChallengesResponse.prototype['links'] = undefined;

/**
 * @member {module:model/PagingInformation} meta
 */
GameCenterChallengesResponse.prototype['meta'] = undefined;






export default GameCenterChallengesResponse;

