/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GameCenterAchievementRelationshipsGameCenterGroup from './GameCenterAchievementRelationshipsGameCenterGroup';
import GameCenterAchievementReleaseRelationshipsGameCenterDetail from './GameCenterAchievementReleaseRelationshipsGameCenterDetail';
import GameCenterActivityRelationshipsAchievements from './GameCenterActivityRelationshipsAchievements';
import GameCenterActivityRelationshipsLeaderboards from './GameCenterActivityRelationshipsLeaderboards';
import GameCenterActivityRelationshipsVersions from './GameCenterActivityRelationshipsVersions';

/**
 * The GameCenterActivityRelationships model module.
 * @module model/GameCenterActivityRelationships
 * @version 4.1
 */
class GameCenterActivityRelationships {
    /**
     * Constructs a new <code>GameCenterActivityRelationships</code>.
     * @alias module:model/GameCenterActivityRelationships
     */
    constructor() { 
        
        GameCenterActivityRelationships.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameCenterActivityRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterActivityRelationships} obj Optional instance to populate.
     * @return {module:model/GameCenterActivityRelationships} The populated <code>GameCenterActivityRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterActivityRelationships();

            if (data.hasOwnProperty('gameCenterDetail')) {
                obj['gameCenterDetail'] = GameCenterAchievementReleaseRelationshipsGameCenterDetail.constructFromObject(data['gameCenterDetail']);
            }
            if (data.hasOwnProperty('gameCenterGroup')) {
                obj['gameCenterGroup'] = GameCenterAchievementRelationshipsGameCenterGroup.constructFromObject(data['gameCenterGroup']);
            }
            if (data.hasOwnProperty('achievements')) {
                obj['achievements'] = GameCenterActivityRelationshipsAchievements.constructFromObject(data['achievements']);
            }
            if (data.hasOwnProperty('leaderboards')) {
                obj['leaderboards'] = GameCenterActivityRelationshipsLeaderboards.constructFromObject(data['leaderboards']);
            }
            if (data.hasOwnProperty('versions')) {
                obj['versions'] = GameCenterActivityRelationshipsVersions.constructFromObject(data['versions']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterActivityRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterActivityRelationships</code>.
     */
    static validateJSON(data) {
        // validate the optional field `gameCenterDetail`
        if (data['gameCenterDetail']) { // data not null
          GameCenterAchievementReleaseRelationshipsGameCenterDetail.validateJSON(data['gameCenterDetail']);
        }
        // validate the optional field `gameCenterGroup`
        if (data['gameCenterGroup']) { // data not null
          GameCenterAchievementRelationshipsGameCenterGroup.validateJSON(data['gameCenterGroup']);
        }
        // validate the optional field `achievements`
        if (data['achievements']) { // data not null
          GameCenterActivityRelationshipsAchievements.validateJSON(data['achievements']);
        }
        // validate the optional field `leaderboards`
        if (data['leaderboards']) { // data not null
          GameCenterActivityRelationshipsLeaderboards.validateJSON(data['leaderboards']);
        }
        // validate the optional field `versions`
        if (data['versions']) { // data not null
          GameCenterActivityRelationshipsVersions.validateJSON(data['versions']);
        }

        return true;
    }


}



/**
 * @member {module:model/GameCenterAchievementReleaseRelationshipsGameCenterDetail} gameCenterDetail
 */
GameCenterActivityRelationships.prototype['gameCenterDetail'] = undefined;

/**
 * @member {module:model/GameCenterAchievementRelationshipsGameCenterGroup} gameCenterGroup
 */
GameCenterActivityRelationships.prototype['gameCenterGroup'] = undefined;

/**
 * @member {module:model/GameCenterActivityRelationshipsAchievements} achievements
 */
GameCenterActivityRelationships.prototype['achievements'] = undefined;

/**
 * @member {module:model/GameCenterActivityRelationshipsLeaderboards} leaderboards
 */
GameCenterActivityRelationships.prototype['leaderboards'] = undefined;

/**
 * @member {module:model/GameCenterActivityRelationshipsVersions} versions
 */
GameCenterActivityRelationships.prototype['versions'] = undefined;






export default GameCenterActivityRelationships;

