/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GameCenterActivityCreateRequestData from './GameCenterActivityCreateRequestData';

/**
 * The GameCenterActivityCreateRequest model module.
 * @module model/GameCenterActivityCreateRequest
 * @version 4.1
 */
class GameCenterActivityCreateRequest {
    /**
     * Constructs a new <code>GameCenterActivityCreateRequest</code>.
     * @alias module:model/GameCenterActivityCreateRequest
     * @param data {module:model/GameCenterActivityCreateRequestData} 
     */
    constructor(data) { 
        
        GameCenterActivityCreateRequest.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>GameCenterActivityCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterActivityCreateRequest} obj Optional instance to populate.
     * @return {module:model/GameCenterActivityCreateRequest} The populated <code>GameCenterActivityCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterActivityCreateRequest();

            if (data.hasOwnProperty('data')) {
                obj['data'] = GameCenterActivityCreateRequestData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterActivityCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterActivityCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GameCenterActivityCreateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          GameCenterActivityCreateRequestData.validateJSON(data['data']);
        }

        return true;
    }


}

GameCenterActivityCreateRequest.RequiredProperties = ["data"];

/**
 * @member {module:model/GameCenterActivityCreateRequestData} data
 */
GameCenterActivityCreateRequest.prototype['data'] = undefined;






export default GameCenterActivityCreateRequest;

