/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GameCenterAchievementRelationshipsGameCenterGroup from './GameCenterAchievementRelationshipsGameCenterGroup';
import GameCenterAchievementReleaseRelationshipsGameCenterDetail from './GameCenterAchievementReleaseRelationshipsGameCenterDetail';
import GameCenterChallengeRelationshipsLeaderboard from './GameCenterChallengeRelationshipsLeaderboard';
import GameCenterChallengeRelationshipsVersions from './GameCenterChallengeRelationshipsVersions';

/**
 * The GameCenterChallengeRelationships model module.
 * @module model/GameCenterChallengeRelationships
 * @version 4.1
 */
class GameCenterChallengeRelationships {
    /**
     * Constructs a new <code>GameCenterChallengeRelationships</code>.
     * @alias module:model/GameCenterChallengeRelationships
     */
    constructor() { 
        
        GameCenterChallengeRelationships.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameCenterChallengeRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterChallengeRelationships} obj Optional instance to populate.
     * @return {module:model/GameCenterChallengeRelationships} The populated <code>GameCenterChallengeRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterChallengeRelationships();

            if (data.hasOwnProperty('gameCenterDetail')) {
                obj['gameCenterDetail'] = GameCenterAchievementReleaseRelationshipsGameCenterDetail.constructFromObject(data['gameCenterDetail']);
            }
            if (data.hasOwnProperty('gameCenterGroup')) {
                obj['gameCenterGroup'] = GameCenterAchievementRelationshipsGameCenterGroup.constructFromObject(data['gameCenterGroup']);
            }
            if (data.hasOwnProperty('versions')) {
                obj['versions'] = GameCenterChallengeRelationshipsVersions.constructFromObject(data['versions']);
            }
            if (data.hasOwnProperty('leaderboard')) {
                obj['leaderboard'] = GameCenterChallengeRelationshipsLeaderboard.constructFromObject(data['leaderboard']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterChallengeRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterChallengeRelationships</code>.
     */
    static validateJSON(data) {
        // validate the optional field `gameCenterDetail`
        if (data['gameCenterDetail']) { // data not null
          GameCenterAchievementReleaseRelationshipsGameCenterDetail.validateJSON(data['gameCenterDetail']);
        }
        // validate the optional field `gameCenterGroup`
        if (data['gameCenterGroup']) { // data not null
          GameCenterAchievementRelationshipsGameCenterGroup.validateJSON(data['gameCenterGroup']);
        }
        // validate the optional field `versions`
        if (data['versions']) { // data not null
          GameCenterChallengeRelationshipsVersions.validateJSON(data['versions']);
        }
        // validate the optional field `leaderboard`
        if (data['leaderboard']) { // data not null
          GameCenterChallengeRelationshipsLeaderboard.validateJSON(data['leaderboard']);
        }

        return true;
    }


}



/**
 * @member {module:model/GameCenterAchievementReleaseRelationshipsGameCenterDetail} gameCenterDetail
 */
GameCenterChallengeRelationships.prototype['gameCenterDetail'] = undefined;

/**
 * @member {module:model/GameCenterAchievementRelationshipsGameCenterGroup} gameCenterGroup
 */
GameCenterChallengeRelationships.prototype['gameCenterGroup'] = undefined;

/**
 * @member {module:model/GameCenterChallengeRelationshipsVersions} versions
 */
GameCenterChallengeRelationships.prototype['versions'] = undefined;

/**
 * @member {module:model/GameCenterChallengeRelationshipsLeaderboard} leaderboard
 */
GameCenterChallengeRelationships.prototype['leaderboard'] = undefined;






export default GameCenterChallengeRelationships;

