/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters from './AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters';
import GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult from './GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult';

/**
 * The GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions model module.
 * @module model/GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions
 * @version 4.1
 */
class GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions {
    /**
     * Constructs a new <code>GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions</code>.
     * @alias module:model/GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions
     */
    constructor() { 
        
        GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions} obj Optional instance to populate.
     * @return {module:model/GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions} The populated <code>GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions();

            if (data.hasOwnProperty('result')) {
                obj['result'] = GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult.constructFromObject(data['result']);
            }
            if (data.hasOwnProperty('gameCenterDetail')) {
                obj['gameCenterDetail'] = AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters.constructFromObject(data['gameCenterDetail']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions</code>.
     */
    static validateJSON(data) {
        // validate the optional field `result`
        if (data['result']) { // data not null
          GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult.validateJSON(data['result']);
        }
        // validate the optional field `gameCenterDetail`
        if (data['gameCenterDetail']) { // data not null
          AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters.validateJSON(data['gameCenterDetail']);
        }

        return true;
    }


}



/**
 * @member {module:model/GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult} result
 */
GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions.prototype['result'] = undefined;

/**
 * @member {module:model/AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters} gameCenterDetail
 */
GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions.prototype['gameCenterDetail'] = undefined;






export default GameCenterMatchmakingQueueRequestsV1MetricResponseDataInnerDimensions;

