/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GameCenterMatchmakingTeamAssignment from './GameCenterMatchmakingTeamAssignment';

/**
 * The GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner model module.
 * @module model/GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner
 * @version 4.1
 */
class GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner {
    /**
     * Constructs a new <code>GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner</code>.
     * @alias module:model/GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner
     */
    constructor() { 
        
        GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner} obj Optional instance to populate.
     * @return {module:model/GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner} The populated <code>GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner();

            if (data.hasOwnProperty('requestName')) {
                obj['requestName'] = ApiClient.convertToType(data['requestName'], 'String');
            }
            if (data.hasOwnProperty('teamAssignments')) {
                obj['teamAssignments'] = ApiClient.convertToType(data['teamAssignments'], [GameCenterMatchmakingTeamAssignment]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['requestName'] && !(typeof data['requestName'] === 'string' || data['requestName'] instanceof String)) {
            throw new Error("Expected the field `requestName` to be a primitive type in the JSON string but got " + data['requestName']);
        }
        if (data['teamAssignments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['teamAssignments'])) {
                throw new Error("Expected the field `teamAssignments` to be an array in the JSON data but got " + data['teamAssignments']);
            }
            // validate the optional field `teamAssignments` (array)
            for (const item of data['teamAssignments']) {
                GameCenterMatchmakingTeamAssignment.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} requestName
 */
GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner.prototype['requestName'] = undefined;

/**
 * @member {Array.<module:model/GameCenterMatchmakingTeamAssignment>} teamAssignments
 */
GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner.prototype['teamAssignments'] = undefined;






export default GameCenterMatchmakingRuleSetTestAttributesMatchmakingResultsInnerInner;

