/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPoints from './GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPoints';
import GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions from './GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions';

/**
 * The GameCenterMatchmakingAppRequestsV1MetricResponseDataInner model module.
 * @module model/GameCenterMatchmakingAppRequestsV1MetricResponseDataInner
 * @version 4.1
 */
class GameCenterMatchmakingAppRequestsV1MetricResponseDataInner {
    /**
     * Constructs a new <code>GameCenterMatchmakingAppRequestsV1MetricResponseDataInner</code>.
     * @alias module:model/GameCenterMatchmakingAppRequestsV1MetricResponseDataInner
     */
    constructor() { 
        
        GameCenterMatchmakingAppRequestsV1MetricResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameCenterMatchmakingAppRequestsV1MetricResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterMatchmakingAppRequestsV1MetricResponseDataInner} obj Optional instance to populate.
     * @return {module:model/GameCenterMatchmakingAppRequestsV1MetricResponseDataInner} The populated <code>GameCenterMatchmakingAppRequestsV1MetricResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterMatchmakingAppRequestsV1MetricResponseDataInner();

            if (data.hasOwnProperty('dataPoints')) {
                obj['dataPoints'] = GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPoints.constructFromObject(data['dataPoints']);
            }
            if (data.hasOwnProperty('dimensions')) {
                obj['dimensions'] = GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions.constructFromObject(data['dimensions']);
            }
            if (data.hasOwnProperty('granularity')) {
                obj['granularity'] = ApiClient.convertToType(data['granularity'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterMatchmakingAppRequestsV1MetricResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterMatchmakingAppRequestsV1MetricResponseDataInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `dataPoints`
        if (data['dataPoints']) { // data not null
          GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPoints.validateJSON(data['dataPoints']);
        }
        // validate the optional field `dimensions`
        if (data['dimensions']) { // data not null
          GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions.validateJSON(data['dimensions']);
        }
        // ensure the json data is a string
        if (data['granularity'] && !(typeof data['granularity'] === 'string' || data['granularity'] instanceof String)) {
            throw new Error("Expected the field `granularity` to be a primitive type in the JSON string but got " + data['granularity']);
        }

        return true;
    }


}



/**
 * @member {module:model/GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDataPoints} dataPoints
 */
GameCenterMatchmakingAppRequestsV1MetricResponseDataInner.prototype['dataPoints'] = undefined;

/**
 * @member {module:model/GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensions} dimensions
 */
GameCenterMatchmakingAppRequestsV1MetricResponseDataInner.prototype['dimensions'] = undefined;

/**
 * @member {module:model/GameCenterMatchmakingAppRequestsV1MetricResponseDataInner.GranularityEnum} granularity
 */
GameCenterMatchmakingAppRequestsV1MetricResponseDataInner.prototype['granularity'] = undefined;





/**
 * Allowed values for the <code>granularity</code> property.
 * @enum {String}
 * @readonly
 */
GameCenterMatchmakingAppRequestsV1MetricResponseDataInner['GranularityEnum'] = {

    /**
     * value: "P1D"
     * @const
     */
    "P1D": "P1D",

    /**
     * value: "PT1H"
     * @const
     */
    "PT1H": "PT1H",

    /**
     * value: "PT15M"
     * @const
     */
    "PT15M": "PT15M"
};



export default GameCenterMatchmakingAppRequestsV1MetricResponseDataInner;

