/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GameCenterDetailAttributes model module.
 * @module model/GameCenterDetailAttributes
 * @version 4.1
 */
class GameCenterDetailAttributes {
    /**
     * Constructs a new <code>GameCenterDetailAttributes</code>.
     * @alias module:model/GameCenterDetailAttributes
     */
    constructor() { 
        
        GameCenterDetailAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameCenterDetailAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterDetailAttributes} obj Optional instance to populate.
     * @return {module:model/GameCenterDetailAttributes} The populated <code>GameCenterDetailAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterDetailAttributes();

            if (data.hasOwnProperty('arcadeEnabled')) {
                obj['arcadeEnabled'] = ApiClient.convertToType(data['arcadeEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('challengeEnabled')) {
                obj['challengeEnabled'] = ApiClient.convertToType(data['challengeEnabled'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterDetailAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterDetailAttributes</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} arcadeEnabled
 */
GameCenterDetailAttributes.prototype['arcadeEnabled'] = undefined;

/**
 * @member {Boolean} challengeEnabled
 */
GameCenterDetailAttributes.prototype['challengeEnabled'] = undefined;






export default GameCenterDetailAttributes;

