/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Property from './Property';

/**
 * The GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes model module.
 * @module model/GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes
 * @version 4.1
 */
class GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes {
    /**
     * Constructs a new <code>GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes</code>.
     * @alias module:model/GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes
     * @param playerId {String} 
     */
    constructor(playerId) { 
        
        GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes.initialize(this, playerId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, playerId) { 
        obj['playerId'] = playerId;
    }

    /**
     * Constructs a <code>GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes} obj Optional instance to populate.
     * @return {module:model/GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes} The populated <code>GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes();

            if (data.hasOwnProperty('playerId')) {
                obj['playerId'] = ApiClient.convertToType(data['playerId'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [Property]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['playerId'] && !(typeof data['playerId'] === 'string' || data['playerId'] instanceof String)) {
            throw new Error("Expected the field `playerId` to be a primitive type in the JSON string but got " + data['playerId']);
        }
        if (data['properties']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['properties'])) {
                throw new Error("Expected the field `properties` to be an array in the JSON data but got " + data['properties']);
            }
            // validate the optional field `properties` (array)
            for (const item of data['properties']) {
                Property.validateJSON(item);
            };
        }

        return true;
    }


}

GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes.RequiredProperties = ["playerId"];

/**
 * @member {String} playerId
 */
GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes.prototype['playerId'] = undefined;

/**
 * @member {Array.<module:model/Property>} properties
 */
GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes.prototype['properties'] = undefined;






export default GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes;

