/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GameCenterChallengeImageCreateRequestDataRelationshipsVersion from './GameCenterChallengeImageCreateRequestDataRelationshipsVersion';
import GameCenterChallengeLocalizationRelationshipsImage from './GameCenterChallengeLocalizationRelationshipsImage';

/**
 * The GameCenterChallengeLocalizationRelationships model module.
 * @module model/GameCenterChallengeLocalizationRelationships
 * @version 4.1
 */
class GameCenterChallengeLocalizationRelationships {
    /**
     * Constructs a new <code>GameCenterChallengeLocalizationRelationships</code>.
     * @alias module:model/GameCenterChallengeLocalizationRelationships
     */
    constructor() { 
        
        GameCenterChallengeLocalizationRelationships.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameCenterChallengeLocalizationRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterChallengeLocalizationRelationships} obj Optional instance to populate.
     * @return {module:model/GameCenterChallengeLocalizationRelationships} The populated <code>GameCenterChallengeLocalizationRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterChallengeLocalizationRelationships();

            if (data.hasOwnProperty('version')) {
                obj['version'] = GameCenterChallengeImageCreateRequestDataRelationshipsVersion.constructFromObject(data['version']);
            }
            if (data.hasOwnProperty('image')) {
                obj['image'] = GameCenterChallengeLocalizationRelationshipsImage.constructFromObject(data['image']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterChallengeLocalizationRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterChallengeLocalizationRelationships</code>.
     */
    static validateJSON(data) {
        // validate the optional field `version`
        if (data['version']) { // data not null
          GameCenterChallengeImageCreateRequestDataRelationshipsVersion.validateJSON(data['version']);
        }
        // validate the optional field `image`
        if (data['image']) { // data not null
          GameCenterChallengeLocalizationRelationshipsImage.validateJSON(data['image']);
        }

        return true;
    }


}



/**
 * @member {module:model/GameCenterChallengeImageCreateRequestDataRelationshipsVersion} version
 */
GameCenterChallengeLocalizationRelationships.prototype['version'] = undefined;

/**
 * @member {module:model/GameCenterChallengeLocalizationRelationshipsImage} image
 */
GameCenterChallengeLocalizationRelationships.prototype['image'] = undefined;






export default GameCenterChallengeLocalizationRelationships;

