/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GameCenterLeaderboardSetAttributes model module.
 * @module model/GameCenterLeaderboardSetAttributes
 * @version 4.1
 */
class GameCenterLeaderboardSetAttributes {
    /**
     * Constructs a new <code>GameCenterLeaderboardSetAttributes</code>.
     * @alias module:model/GameCenterLeaderboardSetAttributes
     */
    constructor() { 
        
        GameCenterLeaderboardSetAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GameCenterLeaderboardSetAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GameCenterLeaderboardSetAttributes} obj Optional instance to populate.
     * @return {module:model/GameCenterLeaderboardSetAttributes} The populated <code>GameCenterLeaderboardSetAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GameCenterLeaderboardSetAttributes();

            if (data.hasOwnProperty('referenceName')) {
                obj['referenceName'] = ApiClient.convertToType(data['referenceName'], 'String');
            }
            if (data.hasOwnProperty('vendorIdentifier')) {
                obj['vendorIdentifier'] = ApiClient.convertToType(data['vendorIdentifier'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GameCenterLeaderboardSetAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GameCenterLeaderboardSetAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['referenceName'] && !(typeof data['referenceName'] === 'string' || data['referenceName'] instanceof String)) {
            throw new Error("Expected the field `referenceName` to be a primitive type in the JSON string but got " + data['referenceName']);
        }
        // ensure the json data is a string
        if (data['vendorIdentifier'] && !(typeof data['vendorIdentifier'] === 'string' || data['vendorIdentifier'] instanceof String)) {
            throw new Error("Expected the field `vendorIdentifier` to be a primitive type in the JSON string but got " + data['vendorIdentifier']);
        }

        return true;
    }


}



/**
 * @member {String} referenceName
 */
GameCenterLeaderboardSetAttributes.prototype['referenceName'] = undefined;

/**
 * @member {String} vendorIdentifier
 */
GameCenterLeaderboardSetAttributes.prototype['vendorIdentifier'] = undefined;






export default GameCenterLeaderboardSetAttributes;

