/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InAppPurchaseV2RelationshipsContentData model module.
 * @module model/InAppPurchaseV2RelationshipsContentData
 * @version 4.1
 */
class InAppPurchaseV2RelationshipsContentData {
    /**
     * Constructs a new <code>InAppPurchaseV2RelationshipsContentData</code>.
     * @alias module:model/InAppPurchaseV2RelationshipsContentData
     * @param type {module:model/InAppPurchaseV2RelationshipsContentData.TypeEnum} 
     * @param id {String} 
     */
    constructor(type, id) { 
        
        InAppPurchaseV2RelationshipsContentData.initialize(this, type, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, id) { 
        obj['type'] = type;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>InAppPurchaseV2RelationshipsContentData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InAppPurchaseV2RelationshipsContentData} obj Optional instance to populate.
     * @return {module:model/InAppPurchaseV2RelationshipsContentData} The populated <code>InAppPurchaseV2RelationshipsContentData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InAppPurchaseV2RelationshipsContentData();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InAppPurchaseV2RelationshipsContentData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InAppPurchaseV2RelationshipsContentData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InAppPurchaseV2RelationshipsContentData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}

InAppPurchaseV2RelationshipsContentData.RequiredProperties = ["type", "id"];

/**
 * @member {module:model/InAppPurchaseV2RelationshipsContentData.TypeEnum} type
 */
InAppPurchaseV2RelationshipsContentData.prototype['type'] = undefined;

/**
 * @member {String} id
 */
InAppPurchaseV2RelationshipsContentData.prototype['id'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
InAppPurchaseV2RelationshipsContentData['TypeEnum'] = {

    /**
     * value: "inAppPurchaseContents"
     * @const
     */
    "inAppPurchaseContents": "inAppPurchaseContents"
};



export default InAppPurchaseV2RelationshipsContentData;

