/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReviewSubmissionItemAttributes model module.
 * @module model/ReviewSubmissionItemAttributes
 * @version 4.1
 */
class ReviewSubmissionItemAttributes {
    /**
     * Constructs a new <code>ReviewSubmissionItemAttributes</code>.
     * @alias module:model/ReviewSubmissionItemAttributes
     */
    constructor() { 
        
        ReviewSubmissionItemAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReviewSubmissionItemAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReviewSubmissionItemAttributes} obj Optional instance to populate.
     * @return {module:model/ReviewSubmissionItemAttributes} The populated <code>ReviewSubmissionItemAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReviewSubmissionItemAttributes();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReviewSubmissionItemAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReviewSubmissionItemAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }

        return true;
    }


}



/**
 * @member {module:model/ReviewSubmissionItemAttributes.StateEnum} state
 */
ReviewSubmissionItemAttributes.prototype['state'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
ReviewSubmissionItemAttributes['StateEnum'] = {

    /**
     * value: "READY_FOR_REVIEW"
     * @const
     */
    "READY_FOR_REVIEW": "READY_FOR_REVIEW",

    /**
     * value: "ACCEPTED"
     * @const
     */
    "ACCEPTED": "ACCEPTED",

    /**
     * value: "APPROVED"
     * @const
     */
    "APPROVED": "APPROVED",

    /**
     * value: "REJECTED"
     * @const
     */
    "REJECTED": "REJECTED",

    /**
     * value: "REMOVED"
     * @const
     */
    "REMOVED": "REMOVED"
};



export default ReviewSubmissionItemAttributes;

