/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocumentLinks from './DocumentLinks';
import SubscriptionIntroductoryOffer from './SubscriptionIntroductoryOffer';
import SubscriptionIntroductoryOffersResponseIncludedInner from './SubscriptionIntroductoryOffersResponseIncludedInner';

/**
 * The SubscriptionIntroductoryOfferResponse model module.
 * @module model/SubscriptionIntroductoryOfferResponse
 * @version 4.1
 */
class SubscriptionIntroductoryOfferResponse {
    /**
     * Constructs a new <code>SubscriptionIntroductoryOfferResponse</code>.
     * @alias module:model/SubscriptionIntroductoryOfferResponse
     * @param data {module:model/SubscriptionIntroductoryOffer} 
     * @param links {module:model/DocumentLinks} 
     */
    constructor(data, links) { 
        
        SubscriptionIntroductoryOfferResponse.initialize(this, data, links);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data, links) { 
        obj['data'] = data;
        obj['links'] = links;
    }

    /**
     * Constructs a <code>SubscriptionIntroductoryOfferResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionIntroductoryOfferResponse} obj Optional instance to populate.
     * @return {module:model/SubscriptionIntroductoryOfferResponse} The populated <code>SubscriptionIntroductoryOfferResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionIntroductoryOfferResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = SubscriptionIntroductoryOffer.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('included')) {
                obj['included'] = ApiClient.convertToType(data['included'], [SubscriptionIntroductoryOffersResponseIncludedInner]);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = DocumentLinks.constructFromObject(data['links']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriptionIntroductoryOfferResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriptionIntroductoryOfferResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubscriptionIntroductoryOfferResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          SubscriptionIntroductoryOffer.validateJSON(data['data']);
        }
        if (data['included']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['included'])) {
                throw new Error("Expected the field `included` to be an array in the JSON data but got " + data['included']);
            }
            // validate the optional field `included` (array)
            for (const item of data['included']) {
                SubscriptionIntroductoryOffersResponseIncludedInner.validateJSON(item);
            };
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          DocumentLinks.validateJSON(data['links']);
        }

        return true;
    }


}

SubscriptionIntroductoryOfferResponse.RequiredProperties = ["data", "links"];

/**
 * @member {module:model/SubscriptionIntroductoryOffer} data
 */
SubscriptionIntroductoryOfferResponse.prototype['data'] = undefined;

/**
 * @member {Array.<module:model/SubscriptionIntroductoryOffersResponseIncludedInner>} included
 */
SubscriptionIntroductoryOfferResponse.prototype['included'] = undefined;

/**
 * @member {module:model/DocumentLinks} links
 */
SubscriptionIntroductoryOfferResponse.prototype['links'] = undefined;






export default SubscriptionIntroductoryOfferResponse;

