/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SubscriptionOfferMode.
* @enum {}
* @readonly
*/
export default class SubscriptionOfferMode {
    
        /**
         * value: "PAY_AS_YOU_GO"
         * @const
         */
        "PAY_AS_YOU_GO" = "PAY_AS_YOU_GO";

    
        /**
         * value: "PAY_UP_FRONT"
         * @const
         */
        "PAY_UP_FRONT" = "PAY_UP_FRONT";

    
        /**
         * value: "FREE_TRIAL"
         * @const
         */
        "FREE_TRIAL" = "FREE_TRIAL";

    

    /**
    * Returns a <code>SubscriptionOfferMode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/SubscriptionOfferMode} The enum <code>SubscriptionOfferMode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

