/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubscriptionUpdateRequestDataAttributes model module.
 * @module model/SubscriptionUpdateRequestDataAttributes
 * @version 4.1
 */
class SubscriptionUpdateRequestDataAttributes {
    /**
     * Constructs a new <code>SubscriptionUpdateRequestDataAttributes</code>.
     * @alias module:model/SubscriptionUpdateRequestDataAttributes
     */
    constructor() { 
        
        SubscriptionUpdateRequestDataAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubscriptionUpdateRequestDataAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionUpdateRequestDataAttributes} obj Optional instance to populate.
     * @return {module:model/SubscriptionUpdateRequestDataAttributes} The populated <code>SubscriptionUpdateRequestDataAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionUpdateRequestDataAttributes();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('familySharable')) {
                obj['familySharable'] = ApiClient.convertToType(data['familySharable'], 'Boolean');
            }
            if (data.hasOwnProperty('subscriptionPeriod')) {
                obj['subscriptionPeriod'] = ApiClient.convertToType(data['subscriptionPeriod'], 'String');
            }
            if (data.hasOwnProperty('reviewNote')) {
                obj['reviewNote'] = ApiClient.convertToType(data['reviewNote'], 'String');
            }
            if (data.hasOwnProperty('groupLevel')) {
                obj['groupLevel'] = ApiClient.convertToType(data['groupLevel'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriptionUpdateRequestDataAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriptionUpdateRequestDataAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['subscriptionPeriod'] && !(typeof data['subscriptionPeriod'] === 'string' || data['subscriptionPeriod'] instanceof String)) {
            throw new Error("Expected the field `subscriptionPeriod` to be a primitive type in the JSON string but got " + data['subscriptionPeriod']);
        }
        // ensure the json data is a string
        if (data['reviewNote'] && !(typeof data['reviewNote'] === 'string' || data['reviewNote'] instanceof String)) {
            throw new Error("Expected the field `reviewNote` to be a primitive type in the JSON string but got " + data['reviewNote']);
        }

        return true;
    }


}



/**
 * @member {String} name
 */
SubscriptionUpdateRequestDataAttributes.prototype['name'] = undefined;

/**
 * @member {Boolean} familySharable
 */
SubscriptionUpdateRequestDataAttributes.prototype['familySharable'] = undefined;

/**
 * @member {module:model/SubscriptionUpdateRequestDataAttributes.SubscriptionPeriodEnum} subscriptionPeriod
 */
SubscriptionUpdateRequestDataAttributes.prototype['subscriptionPeriod'] = undefined;

/**
 * @member {String} reviewNote
 */
SubscriptionUpdateRequestDataAttributes.prototype['reviewNote'] = undefined;

/**
 * @member {Number} groupLevel
 */
SubscriptionUpdateRequestDataAttributes.prototype['groupLevel'] = undefined;





/**
 * Allowed values for the <code>subscriptionPeriod</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionUpdateRequestDataAttributes['SubscriptionPeriodEnum'] = {

    /**
     * value: "ONE_WEEK"
     * @const
     */
    "ONE_WEEK": "ONE_WEEK",

    /**
     * value: "ONE_MONTH"
     * @const
     */
    "ONE_MONTH": "ONE_MONTH",

    /**
     * value: "TWO_MONTHS"
     * @const
     */
    "TWO_MONTHS": "TWO_MONTHS",

    /**
     * value: "THREE_MONTHS"
     * @const
     */
    "THREE_MONTHS": "THREE_MONTHS",

    /**
     * value: "SIX_MONTHS"
     * @const
     */
    "SIX_MONTHS": "SIX_MONTHS",

    /**
     * value: "ONE_YEAR"
     * @const
     */
    "ONE_YEAR": "ONE_YEAR"
};



export default SubscriptionUpdateRequestDataAttributes;

