/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubscriptionGroupLocalizationCreateRequestDataRelationshipsSubscriptionGroup from './SubscriptionGroupLocalizationCreateRequestDataRelationshipsSubscriptionGroup';

/**
 * The SubscriptionGroupLocalizationCreateRequestDataRelationships model module.
 * @module model/SubscriptionGroupLocalizationCreateRequestDataRelationships
 * @version 4.1
 */
class SubscriptionGroupLocalizationCreateRequestDataRelationships {
    /**
     * Constructs a new <code>SubscriptionGroupLocalizationCreateRequestDataRelationships</code>.
     * @alias module:model/SubscriptionGroupLocalizationCreateRequestDataRelationships
     * @param subscriptionGroup {module:model/SubscriptionGroupLocalizationCreateRequestDataRelationshipsSubscriptionGroup} 
     */
    constructor(subscriptionGroup) { 
        
        SubscriptionGroupLocalizationCreateRequestDataRelationships.initialize(this, subscriptionGroup);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, subscriptionGroup) { 
        obj['subscriptionGroup'] = subscriptionGroup;
    }

    /**
     * Constructs a <code>SubscriptionGroupLocalizationCreateRequestDataRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionGroupLocalizationCreateRequestDataRelationships} obj Optional instance to populate.
     * @return {module:model/SubscriptionGroupLocalizationCreateRequestDataRelationships} The populated <code>SubscriptionGroupLocalizationCreateRequestDataRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionGroupLocalizationCreateRequestDataRelationships();

            if (data.hasOwnProperty('subscriptionGroup')) {
                obj['subscriptionGroup'] = SubscriptionGroupLocalizationCreateRequestDataRelationshipsSubscriptionGroup.constructFromObject(data['subscriptionGroup']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriptionGroupLocalizationCreateRequestDataRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriptionGroupLocalizationCreateRequestDataRelationships</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubscriptionGroupLocalizationCreateRequestDataRelationships.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `subscriptionGroup`
        if (data['subscriptionGroup']) { // data not null
          SubscriptionGroupLocalizationCreateRequestDataRelationshipsSubscriptionGroup.validateJSON(data['subscriptionGroup']);
        }

        return true;
    }


}

SubscriptionGroupLocalizationCreateRequestDataRelationships.RequiredProperties = ["subscriptionGroup"];

/**
 * @member {module:model/SubscriptionGroupLocalizationCreateRequestDataRelationshipsSubscriptionGroup} subscriptionGroup
 */
SubscriptionGroupLocalizationCreateRequestDataRelationships.prototype['subscriptionGroup'] = undefined;






export default SubscriptionGroupLocalizationCreateRequestDataRelationships;

