/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubscriptionOfferCodeOneTimeUseCodeAttributes model module.
 * @module model/SubscriptionOfferCodeOneTimeUseCodeAttributes
 * @version 4.1
 */
class SubscriptionOfferCodeOneTimeUseCodeAttributes {
    /**
     * Constructs a new <code>SubscriptionOfferCodeOneTimeUseCodeAttributes</code>.
     * @alias module:model/SubscriptionOfferCodeOneTimeUseCodeAttributes
     */
    constructor() { 
        
        SubscriptionOfferCodeOneTimeUseCodeAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SubscriptionOfferCodeOneTimeUseCodeAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionOfferCodeOneTimeUseCodeAttributes} obj Optional instance to populate.
     * @return {module:model/SubscriptionOfferCodeOneTimeUseCodeAttributes} The populated <code>SubscriptionOfferCodeOneTimeUseCodeAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionOfferCodeOneTimeUseCodeAttributes();

            if (data.hasOwnProperty('numberOfCodes')) {
                obj['numberOfCodes'] = ApiClient.convertToType(data['numberOfCodes'], 'Number');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'Date');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriptionOfferCodeOneTimeUseCodeAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriptionOfferCodeOneTimeUseCodeAttributes</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} numberOfCodes
 */
SubscriptionOfferCodeOneTimeUseCodeAttributes.prototype['numberOfCodes'] = undefined;

/**
 * @member {Date} createdDate
 */
SubscriptionOfferCodeOneTimeUseCodeAttributes.prototype['createdDate'] = undefined;

/**
 * @member {Date} expirationDate
 */
SubscriptionOfferCodeOneTimeUseCodeAttributes.prototype['expirationDate'] = undefined;

/**
 * @member {Boolean} active
 */
SubscriptionOfferCodeOneTimeUseCodeAttributes.prototype['active'] = undefined;






export default SubscriptionOfferCodeOneTimeUseCodeAttributes;

