/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InAppPurchaseLocalizationAttributes from './InAppPurchaseLocalizationAttributes';
import ResourceLinks from './ResourceLinks';
import SubscriptionAppStoreReviewScreenshotRelationships from './SubscriptionAppStoreReviewScreenshotRelationships';

/**
 * The SubscriptionLocalization model module.
 * @module model/SubscriptionLocalization
 * @version 4.1
 */
class SubscriptionLocalization {
    /**
     * Constructs a new <code>SubscriptionLocalization</code>.
     * @alias module:model/SubscriptionLocalization
     * @param type {module:model/SubscriptionLocalization.TypeEnum} 
     * @param id {String} 
     */
    constructor(type, id) { 
        
        SubscriptionLocalization.initialize(this, type, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, id) { 
        obj['type'] = type;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>SubscriptionLocalization</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionLocalization} obj Optional instance to populate.
     * @return {module:model/SubscriptionLocalization} The populated <code>SubscriptionLocalization</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionLocalization();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = InAppPurchaseLocalizationAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('relationships')) {
                obj['relationships'] = SubscriptionAppStoreReviewScreenshotRelationships.constructFromObject(data['relationships']);
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ResourceLinks.constructFromObject(data['links']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriptionLocalization</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriptionLocalization</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubscriptionLocalization.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          InAppPurchaseLocalizationAttributes.validateJSON(data['attributes']);
        }
        // validate the optional field `relationships`
        if (data['relationships']) { // data not null
          SubscriptionAppStoreReviewScreenshotRelationships.validateJSON(data['relationships']);
        }
        // validate the optional field `links`
        if (data['links']) { // data not null
          ResourceLinks.validateJSON(data['links']);
        }

        return true;
    }


}

SubscriptionLocalization.RequiredProperties = ["type", "id"];

/**
 * @member {module:model/SubscriptionLocalization.TypeEnum} type
 */
SubscriptionLocalization.prototype['type'] = undefined;

/**
 * @member {String} id
 */
SubscriptionLocalization.prototype['id'] = undefined;

/**
 * @member {module:model/InAppPurchaseLocalizationAttributes} attributes
 */
SubscriptionLocalization.prototype['attributes'] = undefined;

/**
 * @member {module:model/SubscriptionAppStoreReviewScreenshotRelationships} relationships
 */
SubscriptionLocalization.prototype['relationships'] = undefined;

/**
 * @member {module:model/ResourceLinks} links
 */
SubscriptionLocalization.prototype['links'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionLocalization['TypeEnum'] = {

    /**
     * value: "subscriptionLocalizations"
     * @const
     */
    "subscriptionLocalizations": "subscriptionLocalizations"
};



export default SubscriptionLocalization;

