/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubscriptionPromotionalOfferInlineCreateAttributes from './SubscriptionPromotionalOfferInlineCreateAttributes';
import SubscriptionPromotionalOfferInlineCreateRelationships from './SubscriptionPromotionalOfferInlineCreateRelationships';

/**
 * The SubscriptionPromotionalOfferInlineCreate model module.
 * @module model/SubscriptionPromotionalOfferInlineCreate
 * @version 4.1
 */
class SubscriptionPromotionalOfferInlineCreate {
    /**
     * Constructs a new <code>SubscriptionPromotionalOfferInlineCreate</code>.
     * @alias module:model/SubscriptionPromotionalOfferInlineCreate
     * @param type {module:model/SubscriptionPromotionalOfferInlineCreate.TypeEnum} 
     * @param attributes {module:model/SubscriptionPromotionalOfferInlineCreateAttributes} 
     */
    constructor(type, attributes) { 
        
        SubscriptionPromotionalOfferInlineCreate.initialize(this, type, attributes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, attributes) { 
        obj['type'] = type;
        obj['attributes'] = attributes;
    }

    /**
     * Constructs a <code>SubscriptionPromotionalOfferInlineCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionPromotionalOfferInlineCreate} obj Optional instance to populate.
     * @return {module:model/SubscriptionPromotionalOfferInlineCreate} The populated <code>SubscriptionPromotionalOfferInlineCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionPromotionalOfferInlineCreate();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = SubscriptionPromotionalOfferInlineCreateAttributes.constructFromObject(data['attributes']);
            }
            if (data.hasOwnProperty('relationships')) {
                obj['relationships'] = SubscriptionPromotionalOfferInlineCreateRelationships.constructFromObject(data['relationships']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubscriptionPromotionalOfferInlineCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubscriptionPromotionalOfferInlineCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubscriptionPromotionalOfferInlineCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `attributes`
        if (data['attributes']) { // data not null
          SubscriptionPromotionalOfferInlineCreateAttributes.validateJSON(data['attributes']);
        }
        // validate the optional field `relationships`
        if (data['relationships']) { // data not null
          SubscriptionPromotionalOfferInlineCreateRelationships.validateJSON(data['relationships']);
        }

        return true;
    }


}

SubscriptionPromotionalOfferInlineCreate.RequiredProperties = ["type", "attributes"];

/**
 * @member {module:model/SubscriptionPromotionalOfferInlineCreate.TypeEnum} type
 */
SubscriptionPromotionalOfferInlineCreate.prototype['type'] = undefined;

/**
 * @member {String} id
 */
SubscriptionPromotionalOfferInlineCreate.prototype['id'] = undefined;

/**
 * @member {module:model/SubscriptionPromotionalOfferInlineCreateAttributes} attributes
 */
SubscriptionPromotionalOfferInlineCreate.prototype['attributes'] = undefined;

/**
 * @member {module:model/SubscriptionPromotionalOfferInlineCreateRelationships} relationships
 */
SubscriptionPromotionalOfferInlineCreate.prototype['relationships'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
SubscriptionPromotionalOfferInlineCreate['TypeEnum'] = {

    /**
     * value: "subscriptionPromotionalOffers"
     * @const
     */
    "subscriptionPromotionalOffers": "subscriptionPromotionalOffers"
};



export default SubscriptionPromotionalOfferInlineCreate;

