/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WebhookPingCreateRequestDataRelationshipsWebhook from './WebhookPingCreateRequestDataRelationshipsWebhook';

/**
 * The WebhookPingCreateRequestDataRelationships model module.
 * @module model/WebhookPingCreateRequestDataRelationships
 * @version 4.1
 */
class WebhookPingCreateRequestDataRelationships {
    /**
     * Constructs a new <code>WebhookPingCreateRequestDataRelationships</code>.
     * @alias module:model/WebhookPingCreateRequestDataRelationships
     * @param webhook {module:model/WebhookPingCreateRequestDataRelationshipsWebhook} 
     */
    constructor(webhook) { 
        
        WebhookPingCreateRequestDataRelationships.initialize(this, webhook);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, webhook) { 
        obj['webhook'] = webhook;
    }

    /**
     * Constructs a <code>WebhookPingCreateRequestDataRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookPingCreateRequestDataRelationships} obj Optional instance to populate.
     * @return {module:model/WebhookPingCreateRequestDataRelationships} The populated <code>WebhookPingCreateRequestDataRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookPingCreateRequestDataRelationships();

            if (data.hasOwnProperty('webhook')) {
                obj['webhook'] = WebhookPingCreateRequestDataRelationshipsWebhook.constructFromObject(data['webhook']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookPingCreateRequestDataRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookPingCreateRequestDataRelationships</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of WebhookPingCreateRequestDataRelationships.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `webhook`
        if (data['webhook']) { // data not null
          WebhookPingCreateRequestDataRelationshipsWebhook.validateJSON(data['webhook']);
        }

        return true;
    }


}

WebhookPingCreateRequestDataRelationships.RequiredProperties = ["webhook"];

/**
 * @member {module:model/WebhookPingCreateRequestDataRelationshipsWebhook} webhook
 */
WebhookPingCreateRequestDataRelationships.prototype['webhook'] = undefined;






export default WebhookPingCreateRequestDataRelationships;

