/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WebhookDeliveryAttributesResponse model module.
 * @module model/WebhookDeliveryAttributesResponse
 * @version 4.1
 */
class WebhookDeliveryAttributesResponse {
    /**
     * Constructs a new <code>WebhookDeliveryAttributesResponse</code>.
     * @alias module:model/WebhookDeliveryAttributesResponse
     */
    constructor() { 
        
        WebhookDeliveryAttributesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WebhookDeliveryAttributesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WebhookDeliveryAttributesResponse} obj Optional instance to populate.
     * @return {module:model/WebhookDeliveryAttributesResponse} The populated <code>WebhookDeliveryAttributesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WebhookDeliveryAttributesResponse();

            if (data.hasOwnProperty('httpStatusCode')) {
                obj['httpStatusCode'] = ApiClient.convertToType(data['httpStatusCode'], 'Number');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WebhookDeliveryAttributesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WebhookDeliveryAttributesResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['body'] && !(typeof data['body'] === 'string' || data['body'] instanceof String)) {
            throw new Error("Expected the field `body` to be a primitive type in the JSON string but got " + data['body']);
        }

        return true;
    }


}



/**
 * @member {Number} httpStatusCode
 */
WebhookDeliveryAttributesResponse.prototype['httpStatusCode'] = undefined;

/**
 * @member {String} body
 */
WebhookDeliveryAttributesResponse.prototype['body'] = undefined;






export default WebhookDeliveryAttributesResponse;

