/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WinBackOfferRelationshipsPrices from './WinBackOfferRelationshipsPrices';

/**
 * The WinBackOfferRelationships model module.
 * @module model/WinBackOfferRelationships
 * @version 4.1
 */
class WinBackOfferRelationships {
    /**
     * Constructs a new <code>WinBackOfferRelationships</code>.
     * @alias module:model/WinBackOfferRelationships
     */
    constructor() { 
        
        WinBackOfferRelationships.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WinBackOfferRelationships</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WinBackOfferRelationships} obj Optional instance to populate.
     * @return {module:model/WinBackOfferRelationships} The populated <code>WinBackOfferRelationships</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WinBackOfferRelationships();

            if (data.hasOwnProperty('prices')) {
                obj['prices'] = WinBackOfferRelationshipsPrices.constructFromObject(data['prices']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WinBackOfferRelationships</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WinBackOfferRelationships</code>.
     */
    static validateJSON(data) {
        // validate the optional field `prices`
        if (data['prices']) { // data not null
          WinBackOfferRelationshipsPrices.validateJSON(data['prices']);
        }

        return true;
    }


}



/**
 * @member {module:model/WinBackOfferRelationshipsPrices} prices
 */
WinBackOfferRelationships.prototype['prices'] = undefined;






export default WinBackOfferRelationships;

