/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IntegerRange from './IntegerRange';
import SubscriptionOfferDuration from './SubscriptionOfferDuration';
import SubscriptionOfferMode from './SubscriptionOfferMode';

/**
 * The WinBackOfferAttributes model module.
 * @module model/WinBackOfferAttributes
 * @version 4.1
 */
class WinBackOfferAttributes {
    /**
     * Constructs a new <code>WinBackOfferAttributes</code>.
     * @alias module:model/WinBackOfferAttributes
     */
    constructor() { 
        
        WinBackOfferAttributes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WinBackOfferAttributes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WinBackOfferAttributes} obj Optional instance to populate.
     * @return {module:model/WinBackOfferAttributes} The populated <code>WinBackOfferAttributes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WinBackOfferAttributes();

            if (data.hasOwnProperty('referenceName')) {
                obj['referenceName'] = ApiClient.convertToType(data['referenceName'], 'String');
            }
            if (data.hasOwnProperty('offerId')) {
                obj['offerId'] = ApiClient.convertToType(data['offerId'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = SubscriptionOfferDuration.constructFromObject(data['duration']);
            }
            if (data.hasOwnProperty('offerMode')) {
                obj['offerMode'] = SubscriptionOfferMode.constructFromObject(data['offerMode']);
            }
            if (data.hasOwnProperty('periodCount')) {
                obj['periodCount'] = ApiClient.convertToType(data['periodCount'], 'Number');
            }
            if (data.hasOwnProperty('customerEligibilityPaidSubscriptionDurationInMonths')) {
                obj['customerEligibilityPaidSubscriptionDurationInMonths'] = ApiClient.convertToType(data['customerEligibilityPaidSubscriptionDurationInMonths'], 'Number');
            }
            if (data.hasOwnProperty('customerEligibilityTimeSinceLastSubscribedInMonths')) {
                obj['customerEligibilityTimeSinceLastSubscribedInMonths'] = IntegerRange.constructFromObject(data['customerEligibilityTimeSinceLastSubscribedInMonths']);
            }
            if (data.hasOwnProperty('customerEligibilityWaitBetweenOffersInMonths')) {
                obj['customerEligibilityWaitBetweenOffersInMonths'] = ApiClient.convertToType(data['customerEligibilityWaitBetweenOffersInMonths'], 'Number');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'String');
            }
            if (data.hasOwnProperty('promotionIntent')) {
                obj['promotionIntent'] = ApiClient.convertToType(data['promotionIntent'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WinBackOfferAttributes</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WinBackOfferAttributes</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['referenceName'] && !(typeof data['referenceName'] === 'string' || data['referenceName'] instanceof String)) {
            throw new Error("Expected the field `referenceName` to be a primitive type in the JSON string but got " + data['referenceName']);
        }
        // ensure the json data is a string
        if (data['offerId'] && !(typeof data['offerId'] === 'string' || data['offerId'] instanceof String)) {
            throw new Error("Expected the field `offerId` to be a primitive type in the JSON string but got " + data['offerId']);
        }
        // validate the optional field `customerEligibilityTimeSinceLastSubscribedInMonths`
        if (data['customerEligibilityTimeSinceLastSubscribedInMonths']) { // data not null
          IntegerRange.validateJSON(data['customerEligibilityTimeSinceLastSubscribedInMonths']);
        }
        // ensure the json data is a string
        if (data['priority'] && !(typeof data['priority'] === 'string' || data['priority'] instanceof String)) {
            throw new Error("Expected the field `priority` to be a primitive type in the JSON string but got " + data['priority']);
        }
        // ensure the json data is a string
        if (data['promotionIntent'] && !(typeof data['promotionIntent'] === 'string' || data['promotionIntent'] instanceof String)) {
            throw new Error("Expected the field `promotionIntent` to be a primitive type in the JSON string but got " + data['promotionIntent']);
        }

        return true;
    }


}



/**
 * @member {String} referenceName
 */
WinBackOfferAttributes.prototype['referenceName'] = undefined;

/**
 * @member {String} offerId
 */
WinBackOfferAttributes.prototype['offerId'] = undefined;

/**
 * @member {module:model/SubscriptionOfferDuration} duration
 */
WinBackOfferAttributes.prototype['duration'] = undefined;

/**
 * @member {module:model/SubscriptionOfferMode} offerMode
 */
WinBackOfferAttributes.prototype['offerMode'] = undefined;

/**
 * @member {Number} periodCount
 */
WinBackOfferAttributes.prototype['periodCount'] = undefined;

/**
 * @member {Number} customerEligibilityPaidSubscriptionDurationInMonths
 */
WinBackOfferAttributes.prototype['customerEligibilityPaidSubscriptionDurationInMonths'] = undefined;

/**
 * @member {module:model/IntegerRange} customerEligibilityTimeSinceLastSubscribedInMonths
 */
WinBackOfferAttributes.prototype['customerEligibilityTimeSinceLastSubscribedInMonths'] = undefined;

/**
 * @member {Number} customerEligibilityWaitBetweenOffersInMonths
 */
WinBackOfferAttributes.prototype['customerEligibilityWaitBetweenOffersInMonths'] = undefined;

/**
 * @member {Date} startDate
 */
WinBackOfferAttributes.prototype['startDate'] = undefined;

/**
 * @member {Date} endDate
 */
WinBackOfferAttributes.prototype['endDate'] = undefined;

/**
 * @member {module:model/WinBackOfferAttributes.PriorityEnum} priority
 */
WinBackOfferAttributes.prototype['priority'] = undefined;

/**
 * @member {module:model/WinBackOfferAttributes.PromotionIntentEnum} promotionIntent
 */
WinBackOfferAttributes.prototype['promotionIntent'] = undefined;





/**
 * Allowed values for the <code>priority</code> property.
 * @enum {String}
 * @readonly
 */
WinBackOfferAttributes['PriorityEnum'] = {

    /**
     * value: "HIGH"
     * @const
     */
    "HIGH": "HIGH",

    /**
     * value: "NORMAL"
     * @const
     */
    "NORMAL": "NORMAL"
};


/**
 * Allowed values for the <code>promotionIntent</code> property.
 * @enum {String}
 * @readonly
 */
WinBackOfferAttributes['PromotionIntentEnum'] = {

    /**
     * value: "NOT_PROMOTED"
     * @const
     */
    "NOT_PROMOTED": "NOT_PROMOTED",

    /**
     * value: "USE_AUTO_GENERATED_ASSETS"
     * @const
     */
    "USE_AUTO_GENERATED_ASSETS": "USE_AUTO_GENERATED_ASSETS"
};



export default WinBackOfferAttributes;

